### ISSUE TITLE
_WD_CapabilitiesAdd discussion

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#103]
Per @TheDcoder on forum --
>  I would like to request adding the `binary` options to the vendor-specific options (similar to `w3c`), it can be used to set the path of the binary executable in Chrome Driver like so:
>
> _WD_CapabilitiesAdd('binary', 'C:\Software\Chromium\bin\chrome.exe')

**Comment by Danp2** [comment]
@mlipok How difficult would it be to rewrite this function so that it isn't  one big If...ElseIf statement? Could the string values being compared to $key be moved into an array where a lookup is performed?

Your thoughts @TheDcoder?

**Comment by TheDcoder** [comment]
@Danp2 That was my initial idea too, but maybe a new function which only adds vendor specific options might be a better idea, that way the developer is in full control :)

Or maybe we could modify the current function's parameter to accept a boolean, it will be a bit messy that way but we won't have to deal with two functions.

**Comment by mlipok** [comment]
I look on this in next 8 hours

**Comment by Danp2** [comment]
@mlipok I merged the fix. 

> How difficult would it be to rewrite this function so that it isn't one big If...ElseIf statement? Could the string values being compared to $key be moved into an array where a lookup is performed?

I still think this is something that should be considered. Ideally it would be data-driven where the array contents would be loaded from a file.

**Comment by mlipok** [comment]
> Ideally it would be data-driven where the array contents would be loaded from a file.

For what purpose would you like to load the configuration from a file?
Is this the only reason for the proposed change?

**Comment by mlipok** [comment]
Take a look on `_WD_CapabilitiesDisplay()` would you like to have something like `_WD_CapabilitiesToString()` ?
Just try to use:
`_ArrayToString($_WD_CAPS__API)`
then save to file and read from file to $_WD_CAPS__API

**Comment by TheDcoder** [comment]
> Ideally it would be data-driven where the array contents would be loaded from a file.

I don't agree with this idea. The capabilities should be generated on-the-fly, they shouldn't be something that the user can edit... if we put it in a file then it is prone to tampering and thus introduces a new point of failure which requires more code for mitigation.

Also not to mention the extra overhead of managing the file :wink:

I like the current approach where the object is created in memory and passed directly to the WebDriver with no disk I/O.

@mlipok What are your thoughts on my idea of adding a new function which will add arguments to the vendor-specific section? It should be fairly easy to implement and it gives the developer more control.

**Comment by mlipok** [comment]
> @mlipok What are your thoughts on my idea of adding a new function which will add arguments to the vendor-specific section? It should be fairly easy to implement and it gives the developer more control.

Check recent commits:
https://github.com/Danp2/WebDriver/commit/3f1d213b69a38c01e5bae3ed57f6843b8d6a6f36
Or just get current version

**Comment by TheDcoder** [comment]
@mlipok I did check it... in fact, I already have that code because I made the change myself locally before I suggested it 😅

It would be nice to have an universal solution like `_WD_CapabilitiesAddVendor` which will add the supplied arguments to the vendor-specific block in the JSON. Right now we are dealing with each option on a case-by-case basis, ideally we should also let the user/developer have full control over it so that they can add any option for advanced use cases (which may be added in the future by web drivers).

**Comment by mlipok** [comment]
take a look to:
`__WD_CapabilitiesInitialize`

```
If StringInStr($s_BrowserType, 'chrome') Then
	$s_SpecificOptions_KeyName = 'goog:chromeOptions'
ElseIf StringInStr($s_BrowserType, 'firefox') Then
	$s_SpecificOptions_KeyName = 'moz:firefoxOptions'
ElseIf StringInStr($s_BrowserType, 'edge') Then
	$s_SpecificOptions_KeyName = 'ms:edgeOptions'
ElseIf $s_MatchType = 'alwaysMatch' And $s_BrowserType = '' Then
	$s_SpecificOptions_KeyName = ''
ElseIf $s_MatchType = 'firstMatch' And $s_BrowserType = '' Then
	Return SetError(2)
EndIf
```

**Comment by mlipok** [comment]
> ideally we should also let the user/developer have full control over it so that they can add any option for advanced use cases (which may be added in the future by web drivers).

New ISSUE ? ... As this was related to 'binary' ?
Or we talk here on global things/concept ?

I globally/conteptually then....

Please provied few examples of capabilities which you want to add to capability string with this UDF.

**Comment by Danp2** [comment]
@TheDcoder 

> I don't agree with this idea.

That's your prerogative. 😝 

> The capabilities should be generated on-the-fly

Agreed. I wasn't proposing otherwise. I was thinking that the functionality of _WD_CapabilitiesAdd could be data driven. After some further thought, I came to the conclusion that this isn't a good idea because it would require the distribution of additional file(s).

> What are your thoughts on my idea of adding a new function which will add arguments to the vendor-specific section? It should be fairly easy to implement and it gives the developer more control.

Ideally this could be accomplished without adding another function. Maybe a way for the script author to specify the destination section?

**Comment by mlipok** [comment]
> @mlipok What are your thoughts on my idea of adding a new function which will add arguments to the vendor-specific section? It should be fairly easy to implement and it gives the developer more control.

I misunderstood you previously.
@Danp2 statement changed my resoning, of your request.

@Danp2 + @TheDcoder 
Please provide few examples of capabilities which you want to add to capability string with this UDF.

Then I will clearly understod what you means.

**Comment by TheDcoder** [comment]
> New ISSUE ? ... As this was related to 'binary' ?
> Or we talk here on global things/concept ?

Danp2 bought it up so I think it's okay if we discuss general concepts.

> Maybe a way for the script author to specify the destination section?

IMO that would be taking it a bit too far, it would be a wrapper to the `Json_Put` function at that point... having a function or a parameter in the current function to specify the destination as the vendor specific options block sounds like a good balance to me.

> Please provied few examples of capabilities which you want to add to capability string with this UDF.

`binary` is the one I originally wanted to use, I don't use a lot of vendor specific capabilities so I can't point of specific examples but the developer could theoretically add any option as per their linking.

Here are all of the Chrome-specific options supported by ChromeDriver: https://chromedriver.chromium.org/capabilities#h.p_ID_106

`detach` and `debuggerAddress` look interesting to me, I'd probably use the first one by default :smile:

**Comment by Danp2** [comment]
@TheDcoder 

> having a function or a parameter in the current function to specify the destination as the vendor specific options block sounds like a good balance to me.

I think we are saying the same thing. I was thinking an optional parameter for _WD_CapabilitiesAdd that would allow the developer to have greater control over the destination section.

> binary is the one I originally wanted to use, I don't use a lot of vendor specific capabilities so I can't point of specific examples but the developer could theoretically add any option as per their liking.

This is a perfect example. If _WD_CapabilitiesAdd supported this optional "section" parameter, then you would have been able to build the correct Capabilities string **without** requiring @mlipok to update the UDF.

**Comment by TheDcoder** [comment]
> I think we are saying the same thing. I was thinking an optional parameter for _WD_CapabilitiesAdd that would allow the developer to have greater control over the destination section.

It's similar, but not the same, my proposal only adds a single flag which will indicate that the destination is the vendor-specific block.

I think your idea is to allow multiple destinations, we could do it by making the new parameter accept a list of ENUMs, but I am not sure if that will be very useful, we also need to consider the extra inconvenience of specifying a full constant or a string against passing a simple boolean.

To be honest I don't really know how the capabilities are designed, are there any other useful blocks? I could think of `alwaysMatch` etc., but I don't really know what it does or if it is useful for us.

**Comment by mlipok** [comment]
> but the developer could theoretically add any option as per their liking.

You mean add new one which not exist currently? If so then wd_capabilities.au3 may require to be suplemented accordingly.

Take a look:
https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1493316

**Comment by mlipok** [comment]
> I could think of `alwaysMatch` etc., but I don't really know what it does or if it is useful for us.

`alwaysMatch` / `firstMatch` are a way to create and advanced capabilities string which will fit for few different scenario.
You could check it on my `Advanced Capabilities example - Work In Progress` at: https://www.autoitscript.com/wiki/WebDriver#Creating_Capabilities_string

**Comment by mlipok** [comment]
@Danp2  please take a look on:
https://github.com/Danp2/WebDriver/pull/102

this is stopping me on making next progress related to:
`adding "excludeSwitches|**extensions|windowTypes**" capability in specific/vendor capabilities `

**Comment by TheDcoder** [comment]
> You mean add new one which not exist currently? If so then wd_capabilities.au3 may require to be suplemented accordingly.

Yes indeed. I guess it depends on the goal of the UDF, do we want to provide a high-level interface to the coder which manages everything or do we want to expose a low-level interface which will assist the coder who would be responsible about what his code does exactly?

We could do a bit of both of course. My suggestion would add a new low-level function. Danp2 is suggesting blending it all in a single function with extra optional parameters.

Personally I'd just add a new function and call it a day, no need to spend a lot of time on it and most coders would be familiar with the advanced capabilities they want anyway :grin:

**Comment by mlipok** [comment]
> To be honest I don't really know how the capabilities are designed, are there any other useful blocks? I could think of `alwaysMatch` etc., but I don't really know what it does or if it is useful for us.

To be honest I do not use them all, so as far as somebody will need them I could not test it to be sure that they works well.

**Comment by mlipok** [comment]
> correct Capabilities string **without** requiring @mlipok to update the UDF.

Any other form will require the same comprehension effort:
- what you want to achieve (understanding WebDriver Capabilites as such I mean in general)
- how the UDF works
- how to complete / correct a UDF
- testing

Let focus on what we have.
If someone make request, we will try to add new Capabilites groups, as I always count on yours help :)

**Comment by mlipok** [comment]
> `detach` and `debuggerAddress` look interesting to me, I'd probably use the first one by default
check this:
change:

`
ElseIf $key = 'w3c' Or $key = 'maxInstances' Or $key = 'binary' Then  ; for adding capability in specific/vendor capabilities for example: goog:chromeOptions
`
to:
`
ElseIf $key = 'w3c' Or $key = 'maxInstances' Or $key = 'binary' Or $key = 'debuggerAddress' Or $key = 'detach' Then  ; for adding "string" or "boolean" capability in specific/vendor capabilities for example: goog:chromeOptions
`
and then use this:

```
_WD_CapabilitiesAdd('debuggerAddress', 'hostname/ip:port')
_WD_CapabilitiesAdd('detach', True)


```

**Comment by TheDcoder** [comment]
@mlipok That's what we are trying to avoid though, from the function becoming a big If statement as said by @Danp2. I am sure it works, but it's not really elegant.

We could put all the vendor specific keys in a static array and compare the key with an array search function to see if it matches any of them.

Or if it were up to me, I'd make a function called `_WD_CapabilitiesAddVendor` which will always add the key to vendor specific block, no need for matching or storing the keys in a filter list :)

```
_WD_CapabilitiesAddVendor('anyThing', 'foobar') ; This will add "anyThing" key with "foobar" as the value in vendor block (goog:chromeOptions)
```

**Comment by mlipok** [comment]
The key feature in Early Beta Version discussed here:
https://www.autoitscript.com/forum/topic/206576-wd_capabilitiesau3-support-topic-early-beta-version-work-in-progress/

was to have one/single function to add capabilities.

> Or if it were up to me, I'd make a function called `_WD_CapabilitiesAddVendor` which will always add the key to vendor specific block, no need for matching or storing the keys in a filter list :)

So it goes against this rule.

> We could put all the vendor specific keys in a static array and compare the key with an array search function to see if it matches any of them.

... and when it matches, what you want to do with it ?
Because I can't see the light in the tunnel, so far I'm wandering in the fog.

And in relation to your own statement:
> the developer could theoretically add any option as per their liking

What then you will need to do with such `static array` ?

**Comment by mlipok** [comment]
> I am sure it works, but it's not really elegant.

The question is whether this code is understandable and can be read normally by human to easily maintain the code.
Because if you make additional levels of abstention by adding `static arrays`, you will have to use this array additionally.
Because the `static array` itself doesn't mean anything, you still need to do some logic for it.
Because of this I asked:
> ... and when it matches, what you want to do with it ?
> What then you will need to do with such `static array` ?

**Comment by TheDcoder** [comment]
> So it goes against this rule.

I see, I wasn't aware of that goal. It's still kind of a single function... you can think of the extra `Vendor` part as an optional parameter :wink:

Adding a new parameter to `_WD_CapabilitiesAdd` could be messy as it has two optional parameters. The decision is up to you though, just wanted to share my opinion :)

> ... and when it matches, what you want to do with it ?
> Because I can't see the light in the tunnel, so far I'm wandering in the fog.

This is just to make the If statement easier to read, we currently need to add a new `Or` expression for every vendor option, it could be done like this:

```
Local Static $aVendorOptions[...] = ['w3c', `binary`, 'etc.']

ElseIf _ArraySearch($aVendorOptions, $key) Then ; for adding capability in specific/vendor capabilities for example: goog:chromeOptions

; This is just an example, I don't know if _ArraySearch exists, but in my example it searches for $key inside array and returns a True value if it matches with a string in the array.
; To add a new vendor option in the future we just expand the  $aVendorOptions array instead of adding new 'Or' expressions to the If condition :)
```

> What then you will need to do with such static array ?

I hope the above example makes it clear what I have in mind, it is only for cosmetic purposes.

**Comment by mlipok** [comment]
For now I see that you again stick with If.. ElseIf....EndIf.

**Comment by mlipok** [comment]
I have some idea, must have few day to clarify.

**Comment by TheDcoder** [comment]
> For now I see that you again stick with If.. ElseIf....EndIf.

They are different ideas which we can implement, this idea just makes it easier to maintain a single function with a filter list.

> I have some idea, must have few day to clarify.

Okay, looking forward to it.

**Comment by Danp2** [comment]
> You could check it on my Advanced Capabilities example - Work In Progress at: https://www.autoitscript.com/wiki/WebDriver#Creating_Capabilities_string

Some feedback for you on this --

- You have an issue with this entry being linked to the Chrome entry just above it (they expand / collapse together)
- That's a huge wall of code. I wonder if it would be better to link to a Github Gist or something similar

**Comment by Danp2** [comment]
> @Danp2 please take a look on: #102
> 
> this is stopping me on making next progress related to: adding "excludeSwitches|**extensions|windowTypes**" capability in specific/vendor capabilities

I don't see why this pending PR would be impacting your progress . Care to elaborate?

Also, see [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) for details on how to request a PR review. 😉

**Comment by mlipok** [comment]
> * You have an issue with this entry being linked to the Chrome entry just above it (they expand / collapse together)

I do not know what exactly you mean, but check again I just make some changes there.

> * That's a huge wall of code. I wonder if it would be better to link to a Github Gist or something similar
For this reason I used spoiler.
Why you do not like this on WiKi ? 
This looks and behave almost the same on GitHub.

**Comment by Danp2** [comment]
> I do not know what exactly you mean, but check again I just make some changes there.

You have two `div` elements with the same id (id="mw-customcollapsible-DebugChrome1"). You need to change the ID for your new Advanced Capabilities section so that it is unique.

> Why you do not like this on WiKi ?

For the reason I already stated... It's a massive wall of text. 😄 My suggestion is to link to GIST (or whatever) so that the wiki doesn't become cumbersome / unusable. But that just my opinion and you can do whatever you choose.

**Comment by Danp2** [comment]
> ```
> Local Static $aVendorOptions[...] = ['w3c', `binary`, 'etc.']
> 
> ElseIf _ArraySearch($aVendorOptions, $key) Then ; for adding capability in specific/vendor capabilities for example: goog:chromeOptions
> ```
> 

This is inline with the direction I was leaning as well.

> I have some idea, must have few day to clarify.

Sounds good. Let us know when you want to discuss further, so that we can hopefully agree on an approach before you spent a bunch of time on a rewrite.

One idea that I've been kicking around is to add an option to _WD_Option that can be used to control how  _WD_CapabilitiesAdd might behave when it encounters a parameter that it doesn't recognize. Some possible options would be 

- generate error (current behavior)
- add to vendor specific section
- Etc

This may not be desirable, but thought I would throw it out there for discussion. 😃

**Comment by mlipok** [comment]
> * generate error (current behavior)

we will stick with this solution, for example :

if user use `maxInstance` instead `maxInstances` should I treat this as a new custom specific capabilities ?

**Comment by mlipok** [comment]
Here is an example what I'm thinking about:
```
#Region - WIP
;~ 	https://sites.google.com/a/chromium.org/chromedriver/capabilities#TOC-Recognized-capabilities
Local $_CAP_NAME, $_CAP_TYPE, $_CAP_SUB_ARRAY
Global Const $s_ListOfSpecific_ChromeOptions__perfLoggingPrefs_Object = _
		[ _
		["enableNetwork", "boolean"], _
		["enablePage", "boolean"], _
		["traceCategories", "string"], _
		["bufferUsageReportingInterval", "positive integer"] _
		]
Global Const $s_ListOfSpecific_ChromeOptions = _
		[ _
		["args", "list of strings"], _
		["binary", "string", Null], _
		["extensions", "list of strings", Null], _
		["localState", "dictionary", Null], _
		["prefs", "dictionary", Null], _
		["detach", "boolean", Null], _
		["debuggerAddress", "list of strings", Null], _
		["excludeSwitches", "list of strings", Null], _
		["minidumpPath", "string", Null], _
		["mobileEmulation", "dictionary", Null], _
		["perfLoggingPrefs", "dictionary", $s_ListOfSpecific_ChromeOptions__perfLoggingPrefs_Object], _
		["windowTypes", "list of strings", Null] _
		]
#EndRegion - WIP


```

**Comment by TheDcoder** [comment]
@mlipok That's a cool way to define a schema, but I think it's overkill for our purpose... also I'd use constants instead of strings for the type values.

Personally I am still leaning towards multiple functions to handle special cases... that's my opinion anyway. I think I have made my position clear, so I'll let you and @Danp2 decide on what's best for the UDF :smile:

**Comment by mlipok** [comment]
> I'd use constants instead of strings for the type values.

Agree I do the same but it was for conceptuall talks only.

> I think it's overkill for our purpose..

It will be the only way to easily add new capabilities.

**Comment by mlipok** [comment]
> Personally I am still leaning towards multiple functions to handle special cases... that's my opinion anyway.

I hope to convince you to my solution as soon as I improve it internally.

Because at the present stage, I do not think that additional functions are needed for the user.

**Comment by mlipok** [comment]
> > Why you do not like this on WiKi ?
> 
> For the reason I already stated... It's a massive wall of text.

Is it still massive wall of text ?

I'm refering to:
https://www.autoitscript.com/wiki/WebDriver_Capabilities#A_complete_working_example

**Comment by Danp2** [comment]
> Is it still massive wall of text ?

No, I thinks it's better since the page is dedicated to Capabilities. However, it does include a whole bunch of options that may not be necessary for just this example.

Also, _WD_Validate_Browser_Driver may not be needed if I'm understanding its functionality correctly. You should be able to do the same thing with _WD_UpdateDriver. See details in 21d7269e620649a3ed87ee73b3edbbeec86c4d7f

**Comment by mlipok** [comment]
> This is a perfect example. If _WD_CapabilitiesAdd supported this optional "section" parameter, then you would have been able to build the correct Capabilities string **without** requiring @mlipok to update the UDF.

This feature is suplemented in: https://github.com/Danp2/au3WebDriver/pull/263

[And mentioned here](https://github.com/Danp2/au3WebDriver/pull/263#issuecomment-1082084032)

**Comment by mlipok** [comment]
> This feature is suplemented in: #263
> 
> [And mentioned/described here](https://github.com/Danp2/au3WebDriver/pull/263#issuecomment-1082084032)

Can we close this ISSUE ?
I mean we should continue only: [PR#263](https://github.com/Danp2/au3WebDriver/pull/263) not [ISSUE#103](https://github.com/Danp2/au3WebDriver/issues/103)
