### ISSUE TITLE
How to deal with multiple selection ?

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#177]
I would recommend that this discussion be moved elsewhere so that this PR doesn't get bogged down any further

_Originally posted by @Danp2 in https://github.com/Danp2/WebDriver/issues/175#issuecomment-1029554335_

And the question was asked here:
https://github.com/Danp2/WebDriver/pull/175#issuecomment-1029538958

> I am wondering how to deal with multiple selection
> 
> ```
> <select id='OptionToChoose' multiple='multiple'>
> ```
> 
> I mean what kind of features will be needed.
> 
> Here is my TESTING script:
> ..........
>

**Comment by mlipok** [comment]
as for now I provide these features:
```AutoIt
;                  |DESELECTALL    - Clear all selections
;                  |MULTISELECT    - Select <option> elements given in 1D array of labels
;                  |OPTIONS        - Retrieves all <option> elements as 2D array containing 4 columns (value, label, index and selected status)
;                  |SELECTALL      - Select all <option> elements
;                  |SELECTEDLABELS - Retrieves labels of selected <option> elements as 1D array
;                  |SELECTEDOPTIONS- Retrieves selected <option> elements as 2D array containing 4 columns (value, label, index and selected status)
````

the other ones are not related to multiple results
```AutoIt
;                  |SELECTEDINDEX  - Retrieves 0-based index of the first selected <option> element
;                  |VALUE          - Retrieves value of the first selected <option> element
```

If anyone has an idea for some additional, you can discuss here.

**Comment by mlipok** [comment]
I plan to close this issue 2 weeks after https://github.com/Danp2/WebDriver/pull/175 will be merged.

**Comment by mlipok** [comment]
Please assign this to me.

**Comment by mlipok** [comment]
Things to test:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#advanced_select_with_multiple_features
How this `<optgroup label="Flying pets">`
will work with WD UDF

**Comment by mlipok** [comment]
> Things to test: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#advanced_select_with_multiple_features How this `<optgroup label="Flying pets">` will work with WD UDF

This is still needed to check.

**Comment by Danp2** [comment]
While testing #325, I noticed that these changes don't respect the disabled state of an option element (`Hamster` in the example). Is this the intended behavior?

**Comment by mlipok** [comment]
The issue is in wd_helper.au3 but maybe it is javascript implementaion in browser ?
This site: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#advanced_select_with_multiple_features
says:
`The "Hamster" option includes a disabled attribute and therefore can't be selected at all.`
But the statement is true only when it comes to selecting manually. I mean that usinsg this JS:
```js
var options = document.getElementsByName("pets").item(0).options; for ( i=0; i<options.length; i++) {options[i].selected = true;};
```

It is possible.
So maybe if we should be right with such assuption (that disabled option should not be selected)
then we can do such change:
```js
var options = document.getElementsByName("pets").item(0).options; for ( i=0; i<options.length; i++) {if (options[i].disabled==false) {options[i].selected = true}};
```

**Comment by mlipok** [comment]
> So maybe if we should be right with such assuption (that disabled option should not be selected) then we can do such change:


it is already proposed in this PR: https://github.com/Danp2/au3WebDriver/pull/330

**Comment by Danp2** [comment]
Also need to check if parent `optgroup` is disabled. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup#examples

**Comment by mlipok** [comment]
as so far I have such testing:
```js
options = document.querySelector("body > select").options
if (options.item(3).parentNode.nodeName = 'OPTGROUP' && options.item(3).parentNode.disabled) {console.log('test')}
```

**Comment by mlipok** [comment]
According to my statement:
https://github.com/Danp2/au3WebDriver/pull/330#issuecomment-1159737804

I think this ISSUE can be closed.

**Comment by mlipok** [comment]
What here ?
