### ISSUE TITLE
More fancy README.md file

### ISSUE THREAD

**Issue by Sven-Seyfert** [Danp2/au3WebDriver#181]
Hi @Danp2 , hi @mlipok ,

I plan to restructure the README.md file a bit. This entry point for the project could be something more appealing ✨, in my opinion.
Before I share a possible design with you I want to ask if I have to be aware of anything regarding the ReadMe? I mean, are there any magical processes or automation stuff to add new created functions to the ReadMe automatically - or similar steps?

If not, I just could adjust the ReadMe, present the approach and possibly after this I will create a PR, am I right 🤞 ?

Best regards
Sven

**Comment by Danp2** [comment]
There isn't any automation currently.

**Comment by Sven-Seyfert** [comment]
Hi to both you @Danp2 and @mlipok 😀 .

I **proudly** present my more up-to-date README.md file which should combine important "Documentation" and "Getting started" information.

### What I did:
- I totally restructured the whole ReadMe.
- I created an logo/icon and favicon => because each **awesome** project needs an logo 😅 .
- I reviewed the wiki page, the old ReadMe information and other linked references to get the newest information.
  - Then I was able to update links and rephrase some parts to increase the understandability (at least I hope so 😁).
  - I also could prepare some sections of the file that will have to be expand.

### But please be aware or don't be scared, I didn't reinvent the wheel:
I tooked much information of the wiki, but the ReadMe shouldn't be any kind of replacement. Only the really important things to start with the project are in the ReadMe represented.

### Now the hardest part:
In case you don't like it at all => I will go and cry 😭 ... no, no worries! Really, if you don't like it at all or some of it please be honest and tell me. I invested much time, but it was a great experience to do the research and the creation of a recommended and good looking entry point of a project "README.md".

Of course I hope it fits into your imagination about the project future, because you know what is the vision - I am only new to it 😀 .

### ✨ [README.md](https://github.com/Sven-Seyfert/WebDriver#readme) ✨

Best regards
Sven

**Comment by Danp2** [comment]
Thanks for your hard work, @Sven-Seyfert. I'll submit some feedback / suggestions once I've had time to review it.

**Comment by Danp2** [comment]
@Sven-Seyfert  I like the direction you are headed. Here is some general feedback --

- External links -- Have you considered having them open a new tab?
- "Function Reference"  link -- This would make more sense if it linked to HTML pages instead of a CHM file
- Discussion threads -- Do these belong here? If yes, I would recommend moving lower in the file and make the section collapsible
- Opera -- See #166. Still think this discussion should occur so that proper support for Opera can be ensured
- Firefox footnote -- Is that even still valid? They are up to v0.30.0
- EdgeHTML -- Is there a reason that we are still including this?
- FAQ section -- Shouldn't these be focused on getting the UDF installed and running?
- Contributing -- Need to create Contributing.md

> Move your desired browser of choice to directory of the wd_*.au3 files.

This should be webdriver, not browser.

**Comment by Sven-Seyfert** [comment]
Hi @Danp2 ,

thanks for your time to review and you feedback 😀 . These are my answers:

> External links -- Have you considered having them open a new tab?

I would love to do this, but I found no working way for this, see stackoverflow discussion:

![grafik](https://user-images.githubusercontent.com/29656921/152974406-3ee3bb8f-e618-4974-a10d-4ba90ba3e43b.png)

https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank

> "Function Reference" link -- This would make more sense if it linked to HTML pages instead of a CHM file

You're right about it. I took this hint over from the wiki page, but it's makes no real sense. I will change it.

> Discussion threads -- Do these belong here? If yes, I would recommend moving lower in the file and make the section collapsible

That's also a case of taken over from the wiki. I guess it's not necessary. But on the other hand I thought it is a good complement to the documentation (mainly the wiki). I am unsure what is to do - remove or move and collapse?

> Opera -- See https://github.com/Danp2/WebDriver/pull/166. Still think this discussion should occur so that proper support for Opera can be ensured

Okay, I wasn't aware of this, because it was "officially" documented at the wiki. But maybe we should go a step back from Opera until we can ensure the support and we have the necessary knowledge and data about Opera? This means, I would remove all Opera references from the ReadMe?!

> Firefox footnote -- Is that even still valid? They are up to v0.30.0

I noticed the v0.30.0 version but I didn't found a statement that the "Microsoft Visual Studio redistributable runtime" isn't necessary anymore => I will double check.

> EdgeHTML -- Is there a reason that we are still including this?

Like before: It's taken over from the wiki which is mainly maintained by @mlipok for the last months. So maybe we could get rid of it or do you disagree @mlipok?

> FAQ section -- Shouldn't these be focused on getting the UDF installed and running?

Funny, because I had the FAQ section located in the [Documentation](https://github.com/Sven-Seyfert/WebDriver/tree/readme-restructuring#documentation) sections, then in the [Usage](https://github.com/Sven-Seyfert/WebDriver/tree/readme-restructuring#usage) section and then I have chosen a separate section for it.

So it's up to you what you prefer 😇 . I personally like the link directly in the navigation (it's more eye catching), but this is only a personal assessment.

> Contributing -- Need to create Contributing.md

Yes absolutly, I know. In my branch there is the CONTRIBUTING.md file (for now only a dummy one).
I hope you would be fine to have something like this. Why, because it's more clear what is expected when you like to contribute and it fit's the recommended GitHub community standards.

![grafik](https://user-images.githubusercontent.com/29656921/152977956-3e3c02d6-15cb-41eb-8910-f2e0706c3f56.png)

> Sven: Move your desired browser of choice to directory of the wd_*.au3 files.
> Dan: This should be webdriver, not browser.

Will do so, thanks.

Again, thanks for the review, for the feedback 👍 .

Best regards
Sven

**Comment by mlipok** [comment]
> Like before: It's taken over from the wiki which is mainly maintained by @mlipok for the last months. So maybe we could get rid of it or do you disagree @mlipok?

Do you mean ditching WiKi in favor of manageable documentation directly from GitHub?

**Comment by Danp2** [comment]
> Do you mean ditching WiKi in favor of manageable documentation directly from GitHub?

I think he was referring to the idea of removing all references to  EdgeHTML in the ReadMe file.

**Comment by Danp2** [comment]
> I would love to do this, but I found no working way for this, see stackoverflow discussion:

OIC. Didn't realize that limitation existed.

>  I am unsure what is to do - remove or move and collapse?

I vote "remove" since we already link to the wiki, where these links originated.

> I would remove all Opera references from the ReadMe?!

I would say yes, remove them for now. We can add them back once further testing / enhancement has been performed to check compatibility with Opera.

>> FAQ section -- Shouldn't these be focused on getting the UDF installed and running?

> Funny, because I had the FAQ section located 

The point I was attempting to make (rather poorly it seems) was that there are entries from the Wiki FAQ that I don't believe belong in the ReadMe FAQ. IMO, the ReadMe FAQ section needs to be focused solely on installation and setup related issues.

**Comment by Sven-Seyfert** [comment]
@mlipok @Danp2 
> Michał: Do you mean ditching WiKi in favor of manageable documentation directly from GitHub?
> Dan: I think he was referring to the idea of removing all references to EdgeHTML in the ReadMe file.

1. Yes I was refering to the idea of removing all references to EdgeHTML.
2. The point to maybe have a wiki for the project direct on GitHub here, should be discussed at some point in the future 😉 .

> I would say yes, remove them for now. We can add them back once further testing / enhancement has been performed to check compatibility with Opera.

Good idea, will do so.

> FAQ topic: The point I was attempting to make (rather poorly it seems) was that there are entries from the Wiki FAQ that I don't believe belong in the ReadMe FAQ. IMO, the ReadMe FAQ section needs to be focused solely on installation and setup related issues.

Oh okay, that is understandable 😀 . I am not sure about usual content of a FAQ. Because it should help to solve problems which are often appear. This can be installation ones or configuration ones or other problems. But I see your point.
Maybe it would be better to move some of the FAQ questions to a section like "best practises" or similar.
IMO a good place would be in the wiki, not in the ReadMe.

**Comment by Sven-Seyfert** [comment]
What do you think about the "logo"?

![](https://raw.githubusercontent.com/Sven-Seyfert/WebDriver/readme-restructuring/images/icon.png)

- [ ] ugly
- [ ] okayish
- [ ] nice
- [ ] different color would be fine
- [ ] I doesn't care

- It consists of the used font of AutoIt and the used font of W3C => "A³" + "WebDriver".
- I thought that was appropriate.
- It's good readable in different sizes and it looks okay in the light or dark mode view.

**Comment by Danp2** [comment]
The logo is fine as far as I'm concerned. I've actually thought about renaming the GH repo to something like `AU3WebDriver`, but I don't know if this would cause any issues with forks, etc.

**Comment by Sven-Seyfert** [comment]
I guess renaming should be fine:

![grafik](https://user-images.githubusercontent.com/29656921/153047172-ea3b9cd5-b727-445b-b8c0-f9f4407c274d.png)

I suggest instead of `AU3WebDriver` the usage of PascalCase like `Au3WebDriver`, but it's up to you Dan 😀 .

**Comment by Sven-Seyfert** [comment]
@Danp2 
> [...] I've actually thought about renaming the GH repo to something like AU3WebDriver, [...]

Now you did the change to: `au3WebDriver` which looks unusal to be me to be honest. What about capital A `Au3WebDriver`?
As a project name it should start with a capital letter in my opionion 🧐 .

**Comment by Danp2** [comment]
> As a project name it should start with a capital letter in my opinion

It's just the name of the repo. Nothing prevents you from adjusting the name in documentation or whatever.

**Comment by Sven-Seyfert** [comment]
> It's just the name of the repo. Nothing prevents you from adjusting the name in documentation or whatever.

Okay, fair enough 👍 .

**Comment by Sven-Seyfert** [comment]
I will close the issue. Further discussions will be surely follow.
