### ISSUE TITLE
_WD_IsLatestRelease() not works

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#191]
after renaming this repository

This following:
https://github.com/Danp2/au3WebDriver/commit/28f0fd0a3032a68f618cedb138f24276a2bb34d4

should be immediately published as a new version.
I mean here:
https://github.com/Danp2/au3WebDriver/releases

**Comment by Sven-Seyfert** [comment]
But why? GitHub will do a redirection by default. No need to hurry or do I miss something?

**Comment by Danp2** [comment]
I think you miss that InetRead() doesn't get redirected.

**Comment by Danp2** [comment]
New release is out.
