### ISSUE TITLE
Contact person email address

### ISSUE THREAD

**Issue by Sven-Seyfert** [Danp2/au3WebDriver#202]
### Is your feature request related to a problem? Please describe

We closed the [PR#199](https://github.com/Danp2/au3WebDriver/pull/199#issue-1137393101) regarding the community standards (by the way: I am pretty happy about it 😁), but we missed the **Code of Conduct** email address placeholder "email@address.com" that has to be replaced by a contact person email address.

### Describe the solution you'd like

I guess @Danp2 should add a email address which could be used to report improper behavior.

### Describe alternatives you've considered

Instead of this we could link and mention the Issue functionality to get in touch with the maintainers.

### Additional context

No.

**Comment by mlipok** [comment]
I do not think that any email adress is needed.
Here any bugs and feature request should be posted directly here on github project.

**Comment by Danp2** [comment]
I was just looking into this myself. I found [this](https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-how-contributors-report-abuse-in-your-organizations-repository), but I don't see this option under the repo's settings.

I do see `Report content` when clicking the ellipsis button in the top right corner.

**Comment by Danp2** [comment]
I just submitted a change that addresses this issue. Let me know if you see any problems with it.

**Comment by Sven-Seyfert** [comment]
Thanks @Danp2 , this is a really nice approach 😊 . I will close the issue now.
