### ISSUE TITLE
_WD_Option $sOption=CONSOLE Why IsInt($vValue) is supported ?

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#206]
### Describe the bug

This is rather Question not Bug.

Why `IsInt($vValue)` is supported  in `_WD_Option`  when `$sOption=CONSOLE` ?

### How to reproduce

currently this is used only in:
```autoit
Func __WD_ConsoleWrite($sMsg)
	If $_WD_CONSOLE = Default Then
		ConsoleWrite($sMsg)
	Else
		FileWrite($_WD_CONSOLE, $sMsg)
	EndIf
EndFunc   ;==>__WD_ConsoleWrite
```

### Expected behavior

```autoit
Func _WD_Option($sOption, $vValue = Default)
......................................................
	Switch $sOption
......................................................
		Case "console"
			If $vValue == "" Then Return $_WD_CONSOLE
			If Not IsString($vValue) Then
				Return SetError(__WD_Error($sFuncName, $_WD_ERROR_InvalidDataType, "(string/int) $vValue: " & $vValue), 0, 0)
			EndIf
			$_WD_CONSOLE = $vValue
......................................................
```
### Screenshots

not needed

### Additional context

I found this when I was working on: https://github.com/Danp2/au3WebDriver/pull/205

### System under test

Please complete the following information.

 not releated

**Comment by Danp2** [comment]
Good question. I honestly don't remember why that was included. I'll have to do some further digging to try to understand why that was included.

**Comment by Danp2** [comment]
I figured it out. FileWrite accepts the file name or a file handle, so that's why we accept an Int variable in this instance.
