### ISSUE TITLE
New ChangeLog type for documentation or project changes?

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#209]
@Sven-Seyfert We currently have entries in the changelog such as --

```
- README.md restructuring
- Files to fulfill the community standards
etc
```

What are your thoughts on moving these to a separate section so that `Added`, `Changed`, etc are focused on UDF functionality rather than project maintenance?

_Originally posted by @Danp2 in https://github.com/Danp2/au3WebDriver/pull/188#r810516459_

**Comment by Danp2** [comment]
Another option would be to use subcategories. Like this --

## [Unreleased]

### Added

- _WD_JsonCookie (mLipok)
- _WD_GetDevicePixelRatio (mLipok)
- _WD_Cookies: Added DeleteAll option (mLipok)
- _WD_ElementSelectAction: Added SelectedIndex option (mLipok)

#### Project

- Files to fulfill the community standards
	- bug_report.md and feature_request.md
	- CODE_OF_CONDUCT.md file
	- PULL_REQUEST_TEMPLATE.md file

### Changed

**Comment by Sven-Seyfert** [comment]
Hi @Danp2 ,

in general there is no hard recommendation about the level of detail of information which should be recorded in a changelog file. So you actually also could ignore project related changes in the changelog file, but I personally prefer your idea about a separate section - "Project" 👍 .

Maybe something like [...]

![grafik](https://user-images.githubusercontent.com/29656921/154820010-7f4edd0b-9d2e-411c-ba65-e43935a81140.png)

[...] on the same level as "Added" or "Changed"

![grafik](https://user-images.githubusercontent.com/29656921/154820044-a8404dbd-ac17-48e4-ae71-00efae26cc1b.png)

> To be honest, I find the idea quite charming and I may use it in my projects too 😀 .

**Comment by Danp2** [comment]
Thanks for the feedback, @Sven-Seyfert. I'll update the changelog to reflect this new section.

**Comment by Danp2** [comment]
@Sven-Seyfert One additional question --

> CONTRIBUTING.md file includes now reference notices to bug report and feature request templates

The word "now" doesn't make sense here. Is it supposed to be "new"?

**Comment by Sven-Seyfert** [comment]
Sorry for the bad english. What I was trying to say is:

CONTRIBUTING.md file now contains references to bug report template and feature request template

Is this better understandable? Hope so 😀 .
