### ISSUE TITLE
mLipok plans for next months

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#219]
### Is your feature request related to a problem? Please describe

Things to do after 'Opera' projects.
Please treat it as a notebook, sketch, draft, remainder.
Please do not analyze before finishing the 'Opera project'.
Please assign this ticket to me.
I just don't want to disrupt the ongoing design work for now, but I also don't want to forget what I want to do in the future.

### Describe the solution you'd like

- [x] 1. review: _WD_Option() for such kind of variables like $_WD_ERROR_MSGBOX which is not possible to set with _WD_Option()  >>> https://github.com/Danp2/au3WebDriver/pull/244 

- [x] 2. refactor: __WD_Error to use also $iExt - currently it use only $iErr >>> https://github.com/Danp2/au3WebDriver/pull/244

- [x] 3. magic number removall : `MsgBox(16, ` >>> https://github.com/Danp2/au3WebDriver/pull/244

- [X] 4a. __WD_ConsoleWrite : preserve `@error` and `@extended` >>> https://github.com/Danp2/au3WebDriver/pull/222

- [X] 4n. __WD_ConsoleWrite: move `@CRLF` to internall processing - not needed in all `__WD_ConsoleWrite` line >>> https://github.com/Danp2/au3WebDriver/pull/242

- [X]  4c. __WD_ConsoleWrite: support for other `@CRLF`  will be needed in case you have your own function defined .... `If IsFunc($_WD_CONSOLE) Then` >>> https://github.com/Danp2/au3WebDriver/pull/242

Example:
```autoit
Global $_WD_CONSOLE_SUFFIX = @crlf

Func __WD_ConsoleWrite($sMsg)
	If IsFunc($_WD_CONSOLE) Then
		Call($_WD_CONSOLE, $sMsg & $_WD_CONSOLE_SUFFIX)
	ElseIf $_WD_CONSOLE = Null Then
		; do nothing
	Else
		FileWrite($_WD_CONSOLE, $sMsg& $_WD_CONSOLE_SUFFIX)
	EndIf
EndFunc   ;==>__WD_ConsoleWrite
```

- [x]  5.  >>> https://github.com/Danp2/au3WebDriver/pull/244
`DllCall("kernel32.dll", "none", "OutputDebugString", "str", $sMsg)` can not be obligatory
It need to have an option to switch it off.
More: it should be switched off by design (get a look for GDPR law act).

- [x]  6.
`_WD_GetBrowserPath()` not always coresponds to `_WD_CapabilitiesAdd('binary','******')` settings

### Describe alternatives you've considered

not releated

### Additional context

not releated

**Comment by Danp2** [comment]
> __WD_ConsoleWrite : preserve `@error` and `@extended`

Can this be done without adding additional parameters to __WD_ConsoleWrite? If not, then I don't think I can support this.

**Comment by mlipok** [comment]
> Can this be done without adding additional parameters to __WD_ConsoleWrite? If not, then I don't think I can support this.

take a look here: [__WD_ConsoleWrite : preserve @error and @extended](https://github.com/Danp2/au3WebDriver/pull/222)
