### ISSUE TITLE
_WD_CreateSession fails to return session ID with Opera web driver 

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#220]
## Bug report

Same issue as described in https://github.com/Danp2/au3WebDriver/issues/20

### How to reproduce

Steps to reproduce the behavior (e.g.):

2. Click on '...'
3. Scroll down to '...'

### System under test

Please complete the following information.

**Comment by Danp2** [comment]
Found that this webdriver has some idiosyncracies --

- Must specify location of webdriver if running 32 bit version (I think I had similar issues with Firefox)
- It accepts both `operaOptions` and `goog:chromeOptions`
- I could only get it to accept `w3c` designation in `goog:chromeOptions`

This works ok for me to at least launch the browser and get a session ID:

```autoti
$sCapabilities = _
'{' & _
'   "capabilities": {' & _
'      "alwaysMatch": {' & _
'         "acceptInsecureCerts": true,' & _
'         "goog:chromeOptions": {' & _
'            "w3c": true, ' & _
'            "binary": "C:\\Program Files\\Opera\\opera.exe" ' & _
'         }' & _
'      }' & _
'   }' & _
'}'
```
Closing this due to solution found.

**Comment by mlipok** [comment]
Thanks.
Working on fixes.
