### ISSUE TITLE
_WD_GetWebDriverVersion: Subscript Used on non-accessible variable

### ISSUE THREAD

**Issue by seadoggie01** [Danp2/au3WebDriver#233]
https://github.com/Danp2/au3WebDriver/blob/789c69bc993dfff6f63038a5fd853083df82e992/wd_helper.au3#L1541

I'm guessing the output of this command doesn't match the regular expression, so it returns false instead of an array. I'm not sure if this has ever happened before or if this should be an issue normally.

**Comment by Danp2** [comment]
Thanks for the report @seadoggie01. Which webdriver were you testing this on?

**Comment by Danp2** [comment]
FWIW, I wasn't able to replicate this. I can see where it might fail if there was an issue with `StdoutRead`. Fixed in https://github.com/Danp2/au3WebDriver/commit/5640412a8fd02f2d92705a1b1b69c97246fba847

**Comment by seadoggie01** [comment]
I've been testing using Edge. I've never seen this issue before though, which was quite strange
