### ISSUE TITLE
What about different driver location ?

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#240]
What about different driver location ?

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/pull/224#discussion_r819389818_

**Comment by Danp2** [comment]
I believe the mistake here is including any modifier because `$_WD_DRIVER` contains the full path to the webdriver executable.

**Comment by mlipok** [comment]
Can you propose a fix for this ?

**Comment by Danp2** [comment]
> $_WD_DRIVER contains the full path to the webdriver executable

Remove `@ScriptDir & "\" & ` from the line `_WinAPI_GetBinaryType(@ScriptDir & "\" & $_WD_DRIVER)`
