### ISSUE TITLE
Code should be reviewed for _ArrayToString usage

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#243]
> We need to be sure that this is no empty one-dimensional array as in other cases this

If you are suggesting that all code should be reviewed for `_ArrayToString` usage, then I would recommend opening a separate issue on this topic.

**RE: I'm not sure if this is required to add checking for all `_ArrayToString` usage, but it will be good to review and chceck**

_Originally posted by @Danp2 in https://github.com/Danp2/au3WebDriver/pull/212#discussion_r819835355_

**Comment by mlipok** [comment]
Please assignthis to me

**Comment by Danp2** [comment]
FWIW, I just checked and didn't find any other instances where _ArrayToString usage was problematic.

**Comment by mlipok** [comment]
Yeah.
It was suplemented "by ocasion" here:
https://github.com/Danp2/au3WebDriver/pull/251/files
