### ISSUE TITLE
$_WD_DEBUG_Info 》__WD_Error

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#245]
Take a look on: [_WD_ElementSelectAction() $sMessage refactoring](https://github.com/Danp2/au3WebDriver/pull/212/commits/122fbcd241e097cbdc131dda8c8cf530dbbf1338)

What you think about the concept to move all this
```autoit
If $_WD_DEBUG = $_WD_DEBUG_Info Then
```

to internall processing into: 
```AutoIt
__WD_Error($sFuncName, $iErr, $sMessage)
```

If you agree then I open separate ISSUE to review all other codes to suplement this kind of scripting/processing.

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/pull/212#discussion_r820113364_

**Comment by mlipok** [comment]
Please assign this to me.

**Comment by mlipok** [comment]
​
What you think about changing name of `__WD_Error()` to `__WD_Debug()`

Look it is related to such processing:
```AutoIt
	Switch $_WD_DEBUG
		Case $_WD_DEBUG_None
		Case $_WD_DEBUG_Error
		Case $_WD_DEBUG_Info
	EndSwitch
```
As you can see it can notify not only about errors, but also put Informational notification.

​

**Comment by Danp2** [comment]
I would suggest leaving it as-is because it isn't a routine for debugging. It is designed to log / display messages related to errors.

**Comment by mlipok** [comment]
Current and previous (few version back) implementation of `__WD_Error()` in case of `$_WD_DEBUG = $_WD_DEBUG_Info`
Will send the message to: `__WD_ConsoleWrite($sMsg)` regardless of whether `$iErr = $_WD_ERROR_Success` or `$iErr <> $_WD_ERROR_Success`

![image](https://user-images.githubusercontent.com/11089482/156952400-2eb82981-2afc-45ee-baa6-d9b7323fbcba.png)

**Comment by mlipok** [comment]
So I suggest that no matter what your intentions are, this function works even if there was no error.

When we to move all this
```autoit
If $_WD_DEBUG = $_WD_DEBUG_Info Then
```
to internall processing into:
```autoit
__WD_Error($sFuncName, $iErr, $sMessage)
```

Then the name of `__WD_Error()` will be confusing because it has a broader meaning.

**Comment by mlipok** [comment]
But firstly I will do all the changes I plan as so far then we back to discussion on changing the name of `__WD_Error()`.
Then If you agree then I also change at one PR also then name of this function.

Are you agree wich such plan?

**Comment by Danp2** [comment]
> Then the name of __WD_Error() will be confusing because it has a broader meaning/usage.

I don't think anyone will care whether we call it __WD_Error, __WD_Debug, or __WD_Whatever. It's only used internally by the UDF itself, so most users won't ever dig into the code enough to encounter this function.

Honestly, I'm ok with leaving it as-is. Also, I don't think __WD_Debug is a better description of what this function does. Something like __WD_LogResults would be a better choice if you still think it needs changed.

**Comment by mlipok** [comment]
`__WD_LogResults` good name , but this lead me to re thinking.
`__WD_Error()` should be used only on the end when `Return SetError(.....)` is used, so the name `__WD_Error()` is adequate.

**Comment by mlipok** [comment]
This is done in:
https://github.com/Danp2/au3WebDriver/pull/247
