### ISSUE TITLE
__WD_Error: Review needed for:  $iErr < 6

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#246]
I think we need to review this. Instead of "6", we could use the defined constant. Also, does this logic still apply? If so, then is 6 still the correct cutoff or has it changed as the UDF has grown?

_Originally posted by @Danp2 in https://github.com/Danp2/au3WebDriver/pull/244#discussion_r820154087_

**Comment by Danp2** [comment]
Closed in https://github.com/Danp2/au3WebDriver/pull/255/commits/fbb367d33eef867db52590e17c3229101b9e62f8
