### ISSUE TITLE
When to reset value of $_WD_HTTPRESULT?

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#249]
I'm wondering whether almost each `_WD_****` function call should clear `$_WD_HTTPRESULT` at start to be sure it is trully `LastHTTPResult` returned by `_WD_LastHTTPResult()` ?

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/pull/247#discussion_r820866604_

**Comment by mlipok** [comment]
Currently it is reset in `__WD_Post()` :
```autoit
Func __WD_Post($sURL, $sData)
	Local Const $sFuncName = "__WD_Post"
	Local $iResult, $sResponseText, $iErr

	If $_WD_DEBUG = $_WD_DEBUG_Info Then
		__WD_ConsoleWrite($sFuncName & ': URL=' & $sURL & "; $sData=" & $sData)
	EndIf

	$_WD_HTTPRESULT = 0
```

**Comment by Danp2** [comment]
Right... each of these functions performs an HTTP request, so it makes sense to me that the variable is reset in each of these functions.

**Comment by mlipok** [comment]
I think that `$_WD_HTTPRESULT` should be like a `@error` it should be reset on each `_WD_***` function call.
It is user/scripter/coder resposibility to check them and store in correct time.

**Comment by Danp2** [comment]
1) There are functions that don't perform any WinHTTP requests (the new _WD_Json* functions for example). Would calling one of these also reset the value of  $_WD_HTTPRESULT?

2) This would be a script breaking change. Therefore, it shouldn't be made without great consideration.

**Comment by mlipok** [comment]
> My approach to it is different: it is making order from previously not fully/correctly specified functionality.

...not fully/correctly specified way of how `$_WD_HTTPRESULT` works/behaves. Last should be really last and you don't need to focus on which `_WD_***` function resets / changes this value. .... nothing more to add here.

**Comment by Danp2** [comment]
Just because it doesn't behave the way you think it should doesn't necessarily make the current implementation wrong. 😉

**Comment by mlipok** [comment]
Yes, I know the current implementation works.... in most cases.  As long as you check the value at the right moment. The question is what is right moment?
If coder is experienced then he will try to do it ASAP.

You can do it right after executing the function or later ......... and here it starts the question, how much other  `_WD_****` code can you use before losing the previous value?

Ok.
We must to slow down 1 day. Let's do 24H brake.

**Comment by mlipok** [comment]
Finally, I will ask one question, how many scripts have you written based on the analysis of this value?

In my case basically none.
They are all based on `@error` analysis only `$_WD_HTTPRESULT` is used only internally in UDF for better way of debug by showing additionall info i logs.

The question is did you use them in any of your main script (outside Au3WebDriver UDF) ?
I think that other user can confirm that they not rely on this value.

I mean it will not be Script Breaking Change as internally UDF will be consistent. Using them out of UDF will give you 0 or value. And it will be still valid.

**Comment by mlipok** [comment]
Btw. we can always resetting this valu not for all functions for example excluding `_WD_Json****`. 
And I hope you agree that this will be a rresonable step forward to reset them in all functions that calls `__WD_Post() __WD_Get() __WD_Delete()`  but in internally in those 3 function.

**Comment by mlipok** [comment]
> Btw. we can always resetting this valu not for all functions for example excluding `_WD_Json****`. And I hope you agree that this will be a rresonable step forward to reset them in all functions that calls `__WD_Post() __WD_Get() __WD_Delete()` but in internally in those 3 function.

Here is changes which i was in my mind: [wd_core.au3 $_WD_HTTPRESULT = 0 presetting](https://github.com/Danp2/au3WebDriver/pull/247/commits/fc584b5698debcc7be8213f91b5a53a6d14d87c0)
Same should be done for other wd udf files but only where `__WD_Post() __WD_Get() __WD_Delete()` is called.

if you check wd_core.au3 then you notice that I omnit function that not use  `__WD_Post() __WD_Get() __WD_Delete()` .

**Comment by Danp2** [comment]
To answer your question, I've used _WD_LastHTTPResult in one place in my main script, and I'm using it immediately affer a call to _WD_Action, so there isn't any issues here. However, that doesn't mean that someone else isn't using it in such a way that your proposed changes will break their scripts.

P.S. What happened to waiting 24 hours?! 😵‍💫 
P.P.S. You misspelled "resetting" 😝 
P.P.P.S. There's no point in resetting the value in __WD_Post/Get/Delete if it is being done separately elsewhere

**Comment by mlipok** [comment]
> To answer your question, I've used _WD_LastHTTPResult in one place in my main script, and I'm using it immediately affer a call to _WD_Action, so there isn't any issues here. However, that doesn't mean that someone else isn't using it in such a way that your proposed changes will break their scripts.

No. Because only those `_WD_***` functionions that relays on `__WD_Post/Get/Delete` will reset this value at start.

> P.S. What happened to waiting 24 hours?! 😵‍💫 

Coca cola + coffee

> P.P.S. You misspelled "resetting" 😝 

again ...... oh crap.

> P.P.P.S. There's no point in resetting the value in __WD_Post/Get/Delete if it is being done separately elsewhere

Sure.

**Comment by mlipok** [comment]
take also look on: `Func _WD_Window`

If you use it like this:

```autoit
_WD_Window($sSession, 'mistake')
```
it will lead to `$_WD_ERROR_InvalidDataType` but  none of `__WD_Post/Get/Delete` will be called so without `$_WD_HTTPRESULT = 0 ; Reseting result of last WinHTTP request` it will still have old values.
And it is getting to more and more diffucult to relays on `$_WD_HTTPRESULT` without resteting them at start.

![image](https://user-images.githubusercontent.com/11089482/157108116-66616ad6-a7ad-48fd-9916-9a7f15b4c39b.png)

**Comment by Danp2** [comment]
> Coca cola + coffee

😆 

> again ...... oh crap.

This would have been easier to fix if it were a 1 line function.

> take also look on: Func _WD_Window

Oh, I understand the problem. I just don't want the "solution" to cause more issues than it fixes.

**Comment by mlipok** [comment]
> Oh, I understand the problem. I just don't want the "solution" to cause more issues than it fixes.

I agree here.
Just give me a day or two to finish my corrections.
Then you will see the whole thing and probably you will point out some further corrections.
But the direction is right.

**Comment by mlipok** [comment]
I think this ISSUE can be closed as all is processing (suplementation is in progress) in https://github.com/Danp2/au3WebDriver/pull/247

**Comment by mlipok** [comment]
> I think this ISSUE can be closed as all is processing (suplementation is in progress) in #247

What is your opinion ?
