### ISSUE TITLE
__WD_CapabilitiesInitialize: Needs to validate result of _ArraySearch

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#250]
### Describe the bug

https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1497963

### How to reproduce

Pass invalid browser name to _WD_CapabilitiesAdd. For example --

` _WD_CapabilitiesAdd('alwaysMatch', 'edge')`

### Expected behavior

The function should return an error instead of generating `Variable subscript badly formatted`

### System under test

Please complete the following information.

- OS: [e.g. Windows 10]
- OS Arch.: [e.g. X64]
- Browser [e.g. firefox]
- Browser version [e.g. 96.0.3]

@mlipok

**Comment by mlipok** [comment]
Please assign to mee.
I will take a look tomorrow.

**Comment by mlipok** [comment]
I found some spare time to fix it.... between drinking cococola and coffe ;)
