### ISSUE TITLE
Cookie deletion is broken

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#261]
@mlipok If you test with Firefox, then the results are what I was expecting. Since some people may already be depending on this functionality, I would suggest that we change the existing code to something like

```autoit
$sResponse = __WD_Delete($_WD_BASE_URL & ":" & $_WD_PORT & "/session/" & $sSession & "/cookie" & ($sOption <> '') ? "/" & $sOption : "")
```

so that it will work correctly for all browsers.

_Originally posted by @Danp2 in https://github.com/Danp2/au3WebDriver/issues/195#issuecomment-1038086089_

**Comment by Danp2** [comment]
Two issues --

1) Needs to still support "delete" command without additional options (this is the original "delete all")
2) New "deleteall" sends the wrong command to webdriver. I believe the fix is to wrap `($sOption <> '') ? "/" & $sOption : "")` in another set of paretheses.

**Comment by mlipok** [comment]
Will check this in next 2 days

**Comment by Danp2** [comment]
Determined that #1 is not an issue.
