### ISSUE TITLE
new console mode $_WD_DEBUG_Full

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#277]
### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. For example: I'm always frustrated when [...] .

### Describe the solution you'd like

I would like to add new enum:
`$_WD_DEBUG_Testing`

in this way:
```autoit
Global Enum _
		$_WD_DEBUG_None = 0, _ ; No logging to console
		$_WD_DEBUG_Error, _    ; logging to console in case of Error
		$_WD_DEBUG_Info, _     ; logging to console with additional information
		$_WD_DEBUG_Testing     ; logging to console with information for the developer of WebDriver UDF
```

and such function:

```autoit
Func __WD_ConsoleTesting($sMsg, $iError = @error, $iExtended = @extended)
	If $_WD_DEBUG = $_WD_DEBUG_Testing Then __WD_ConsoleWrite('TESTING: ' & $sMsg)
	Return SetError($iError, $iExtended)
EndFunc   ;==>__WD_ConsoleWrite
```

Which will be possible to use instead:
```autoit
If Not @Compiled Then ConsoleWrite("! IFNC: TESTING NEW FEATURES #" & @ScriptLineNumber & $s_Parameters_Info & @CRLF)
```

### Describe alternatives you've considered

none

### Additional context

I know that there will be many other place to check/change
For example it will be needed to check all `If $_WD_DEBUG = $_WD_DEBUG_Info Then`

Also in `Func __WD_Error`
```autoit
		Case $_WD_DEBUG_Error, $_WD_DEBUG_Testing
			If $iErr <> $_WD_ERROR_Success Then ContinueCase
```

If you accept this FR then I create PR.

**Comment by mlipok** [comment]
From your statement, I conclude that you accept the change.
I will prepare an appropriate amendment (PR) taking into account your sugestions.

**Comment by mlipok** [comment]
> Maybe `$_WD_DEBUG_Full` or `$_WD_DEBUG_Debug`
> 
> >

`$_WD_DEBUG_Debug` sounds strange, I choose `$_WD_DEBUG_Full`

**Comment by mlipok** [comment]
> Perhaps you meant to add the new debugging mode to the existing `Case $_WD_DEBUG_Info` line?

I think you are right, thanks for pointing it out.
I just didn't have a chance to test it because it was just a concept.

**Comment by mlipok** [comment]
I would like to do also something like:

```autoit
Func __WD_ConsoleInfo($sMsg, $iError = @error, $iExtended = @extended)
	If $_WD_DEBUG = $_WD_DEBUG_Info Then __WD_ConsoleWrite($sMsg)
	Return SetError($iError, $iExtended)
EndFunc   ;==>__WD_ConsoleInfo
```

to avoid multile usage :
```autoit
	If $_WD_DEBUG = $_WD_DEBUG_Info Then
		__WD_ConsoleWrite($sFuncName & .............)
	EndIf
```

**Comment by Danp2** [comment]
> I would like to do also something like: Func __WD_ConsoleInfo(

Instead of adding another function, have you considered modifying __WD_ConsoleWrite to support an optional debugging level parameter? Something like this --

```autoit
Func __WD_ConsoleWrite($sMsg, $iDebugLevel = Default, $iError = @error, $iExtended = @extended)
	If $iDebugLevel = Default Or $_WD_DEBUG >= $iDebugLevel Then
		If IsFunc($_WD_CONSOLE) Then
			Call($_WD_CONSOLE, $sMsg & $_WD_CONSOLE_Suffix)
		ElseIf $_WD_CONSOLE = Null Then
			; do nothing
		Else
			FileWrite($_WD_CONSOLE, $sMsg & $_WD_CONSOLE_Suffix)
		EndIf
	EndIf
	Return SetError($iError, $iExtended)
EndFunc   ;==>__WD_ConsoleWrite
```

Now this --

```autoit
	If $_WD_DEBUG = $_WD_DEBUG_Info Then
		__WD_ConsoleWrite($sFuncName & ': ' & $sResponse)
	EndIf
```

would become this --

```autoit
	__WD_ConsoleWrite($sFuncName & ': ' & $sResponse, $_WD_DEBUG_Info)
```

**Comment by mlipok** [comment]
I would also propose to modify `Func __WD_Error`

in this part:
```autoit
		Case $_WD_DEBUG_Info
			Local $sExtended = (($iExt <> Default) ? (" / " & $iExt) : (""))
			$sMsg = $sWhere & " ==> " & $aWD_ERROR_DESC[$iErr] & " (" & $iErr & $sExtended & ")"
			If $iExt = Default Then $sMsg &= (($_WD_HTTPRESULT) ? (" HTTP status = " & $_WD_HTTPRESULT) : ("")) ; _WD_LastHTTPResult()
			$sMsg &= (($sMessage) ? (" : " & $sMessage) : (""))
			__WD_ConsoleWrite($sMsg)
```

by moving message processing to inner of `__WD_ConsoleWrite()`

**Comment by Danp2** [comment]
> by moving message processing to inner part of __WD_ConsoleWrite()

I'm not sure that I understand. Can you show an example of your proposed change? Also, explain why this change is needed or the benefit it provides.

**Comment by mlipok** [comment]
```autoit
......
......
......
Func __WD_Error($sWhere, $iErr, $sMessage = Default, $iExt = Default)
	Local Const $sFuncName = "__WD_Error"
......
......
......
		Case $_WD_DEBUG_Info
			__WD_ConsoleWrite($sMsg, $iErr, $iExt)
......
......
......
EndFunc __WD_Error
......
......
......
......
Func __WD_ConsoleWrite($sWhere, $sMsg, $iErr = @error, $iExt = @extended)
	Local $sExtended = (($iExt <> Default) ? (" / " & $iExt) : (""))
	$sMsg = $sWhere & " ==> " & $aWD_ERROR_DESC[$iErr] & " (" & $iErr & $sExtended & ")"
	If $iExt = Default Then $sMsg &= (($_WD_HTTPRESULT) ? (" HTTP status = " & $_WD_HTTPRESULT) : ("")) ; _WD_LastHTTPResult()
	$sMsg &= (($sMessage) ? (" : " & $sMessage) : (""))
	
	If IsFunc($_WD_CONSOLE) Then
		Call($_WD_CONSOLE, $sMsg & $_WD_CONSOLE_Suffix)
	ElseIf $_WD_CONSOLE = Null Then
		; do nothing
	Else
		FileWrite($_WD_CONSOLE, $sMsg & $_WD_CONSOLE_Suffix)
	EndIf
	Return SetError($iErr, $iExt)
EndFunc   ;==>__WD_ConsoleWrite
......
......
......
```


> Also, explain why this change is needed or the benefit it provides.

unification, of messages even when you use:
```autoit
	If $_WD_DEBUG = $_WD_DEBUG_Info Then
		__WD_ConsoleWrite($sFuncName & ': ' & $sResponse)
	EndIf
```

**Comment by mlipok** [comment]
> I'm not in agreement on this change. 

ok.

so is it correct to use:
```autoit
__WD_Error($sFuncName, @error, "TESTING NEW FEATURES #" & @ScriptLineNumber & $s_Parameters_Info , @extended)
```
instead:
```autoit
If Not @Compiled Then ConsoleWrite("! IFNC: TESTING NEW FEATURES #" & @ScriptLineNumber & $s_Parameters_Info & @CRLF)
```

which together with:
```autoit
Func __WD_Error($sWhere, $iErr, $sMessage = Default, $iExt = Default)
......
......
......
		Case $_WD_DEBUG_Info, $_WD_DEBUG_Full
......
......
			__WD_ConsoleWrite($sMsg)
......
......
......
EndFunc __WD_Error
````

do the same job as `$iDebugLevel` which was proposed by you in this modyfication:
```autoit
Func __WD_ConsoleWrite($sMsg, $iDebugLevel = Default, $iError = @error, $iExtended = @extended)
```

**Comment by Danp2** [comment]
Yes, that should work. However, you would still need to modify __WD_ConsoleWrite as proposed by me if you want to achieve the following --

> to avoid multiple usage :
	If $_WD_DEBUG = $_WD_DEBUG_Info Then
		__WD_ConsoleWrite($sFuncName & .............)
	EndIf

Now that I think about this further, it seems like you are wanting to use `__WD_Error` for general logging, which isn't its intended purpose. Why not use the proper function, which is `__WD_ConsoleWrite`?

**Comment by mlipok** [comment]
ok so we stick with:
```auotit
Func __WD_ConsoleWrite($sMsg, $iDebugLevel = Default, $iError = @error, $iExtended = @extended)
```
and then I do all my test and I will see if it fits all my needs.
Ok ?

**Comment by mlipok** [comment]
oh... 
I forgot that in such case I will not have this feature:
```AutoIt
Local $sExtended = (($iExt <> Default) ? (" / " & $iExt) : (""))
$sMsg = $sWhere & " ==> " & $aWD_ERROR_DESC[$iErr] & " (" & $iErr & $sExtended & ")"
If $iExt = Default Then $sMsg &= (($_WD_HTTPRESULT) ? (" HTTP status = " & $_WD_HTTPRESULT) : ("")) ; _WD_LastHTTPResult()
$sMsg &= (($sMessage) ? (" : " & $sMessage) : (""))
```

for this reason I was proposing to move them to inner procesing of `__WD_ConsoleWrite()`

**Comment by mlipok** [comment]
> You are trying to make `__WD_ConsoleWrite` into an extension of `__WD_Error`, which is not its intended use. 

No. I want to have `__WD_Error` as it is and use them only in `Return SetError(__WD_Error($sFuncName, .....)`

> And as you've pointed out in your recent edit, it would require a change to every existing instance of __WD_ConsoleWrite, which doesn't make sense to me.

this is not a problem for me to do all the changes.

**Comment by Danp2** [comment]
> No. I want to have __WD_Error as it is and use them only in Return SetError(__WD_Error($sFuncName, .....)

That's not the impression I got when you asked the following --

```text
Is it correct to use:
__WD_Error($sFuncName, @error, "TESTING NEW FEATURES #" &amp; @ScriptLineNumber &amp; $s_Parameters_Info , @extended)
instead:
If Not @Compiled Then ConsoleWrite("! IFNC: TESTING NEW FEATURES #" &amp; @ScriptLineNumber &amp; $s_Parameters_Info &amp; @CRLF)
```

To me, that is you asking if it's ok to use __WD_Error instead of a more general logging option.

> I just need unification for all messages generated by __WD_ConsoleWrite()

I'm not sure that everyone would want or need this. IMO, every message written to a log doesn't need to contain error codes, HTTP status, etc.

Could you accomplish this task using a custom logging function assigned to $_WD_CONSOLE?

**Comment by mlipok** [comment]
I think yes. I accompilish this task in this way I mean still using __WD_ConsoleWrite()

**Comment by mlipok** [comment]
[$_WD_DEBUG_Full support](https://github.com/Danp2/au3WebDriver/pull/279) is only paritailay PR for this PR.


Later I will add new PR related to this:


>> I'm not sure that everyone would want or need this. IMO, every message written to a log doesn't need to contain error codes, HTTP status, etc.
>> Could you accomplish this task using a custom logging function assigned to $_WD_CONSOLE?


> I think yes. I can accompilish this task in this way I mean still using __WD_ConsoleWrite()

**Comment by Danp2** [comment]
#279 should be marked as Draft because:

- it makes changes to __WD_ConsoleWrite that are beyond the scope of what we discussed above
- it doesn't correctly adjust the existing usage of __WD_ConsoleWrite to the new implementation

**Comment by mlipok** [comment]
> * it makes changes to __WD_ConsoleWrite that are beyond the scope of what we discussed above

I revert them back

> * it doesn't correctly adjust the existing usage of __WD_ConsoleWrite to the new implementation

Do not understand, please elaborate.

**Comment by Danp2** [comment]
> I revert them back

> Do not understand what you mean, please elaborate.

I haven't checked your "revert", but what I was trying to indicate above was that there were instances of __WD_ConsoleWrite in other sources files (ie: wd_core, wd_helper, etc) that no longer functioned after your prior revision.

**Comment by mlipok** [comment]
> I haven't checked your "revert", but what I was trying to indicate above was that there were instances of __WD_ConsoleWrite in other sources files (ie: wd_core, wd_helper, etc) that no longer functioned after your prior revision.

Ok.
No problem with reverting.

I will take a look again on this maybe in one of next PR ;)
