### ISSUE TITLE
message written to a log + error codes, HTTP status, etc.

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#280]
Later I will add new PR related to this:

>> I'm not sure that everyone would want or need this. IMO, every message written to a log doesn't need to contain error codes, HTTP status, etc.
>> Could you accomplish this task using a custom logging function assigned to $_WD_CONSOLE?

> I think yes. I can accompilish this task in this way I mean still using __WD_ConsoleWrite()

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/issues/277#issuecomment-1084329195_

**Comment by mlipok** [comment]
When I be ready then I create new PR showing what I mean.

**Comment by Danp2** [comment]
Continue from [here](https://github.com/Danp2/au3WebDriver/pull/290#issuecomment-1098522814) --

> Full ResponseText / Trimmed ResponseText

IMO, adding the word "Full" or "Trimmed" before "ResponseText" isn't needed

> __WD_Post ==> Success (0) HTTP status = 200 : 
> Who matters about RESPONSE text in LOG when Success was taken ?

There may be instances where seeing the full response would be beneficial even if the function call was successful. For example, what if there was a bug in __WD_DetectError where it failed to detect an error? In this case, it would return $_WD_ERROR_Success and seeing the actual response text could help with isolating the issue.

>  If somebody cares then he should put it to LOG on his own.

How would they do that if it isn't being returned by the function?

> HTTP status = 200

I think we previously discussed dropping "HTTP status = xxx" from the logging output. What is your recollection of that discussion?

> I would like to propose such changes:

My thinking is that the amount of logging should increase as the $_WD_DEBUG level increases. So I would propose that the internal UDF functions shouldn't log anything unless $_WD_DEBUG = $_WD_DEBUG_Full. This change would eliminate much of the duplicate out that occurs when $_WD_DEBUG = $_WD_DEBUG_Info.

Think about it and then give me some feedback. 🙂

**Comment by mlipok** [comment]
> My thinking is that the amount of logging should increase as the $_WD_DEBUG level increases. So I would propose that the internal UDF functions shouldn't log anything unless $_WD_DEBUG = $_WD_DEBUG_Full. This change would eliminate much of the duplicate out that occurs when $_WD_DEBUG = $_WD_DEBUG_Info.

Internal ? You mean `__WD_Post/Get/Delete` ?

I have in the background this modification
```autoit


	Local $sMessage = (($iResult Or $_WD_DEBUG > $_WD_DEBUG_Info) ? ("Full ResponseText=" & $sResponseText) : (""))
	Return SetError(__WD_Error($sFuncName, $iResult, $sMessage), 0, $sResponseText)
EndFunc   ;==>__WD_Get


	Local $sMessage = (($iResult Or $_WD_DEBUG > $_WD_DEBUG_Info) ? ("Full ResponseText=" & $sResponseText) : (""))
	Return SetError(__WD_Error($sFuncName, $iResult, $sMessage), 0, $sResponseText)
EndFunc   ;==>__WD_Post


	Local $sMessage = (($iResult Or $_WD_DEBUG > $_WD_DEBUG_Info) ? ("Full ResponseText=" & $sResponseText) : (""))
	Return SetError(__WD_Error($sFuncName, $iResult, $sMessage), 0, $sResponseText)
EndFunc   ;==>__WD_Delete


```

Is this what you was thinking about ?

**Comment by mlipok** [comment]
> > Full ResponseText / Trimmed ResponseText
> 
> IMO, adding the word "Full" or "Trimmed" before "ResponseText" isn't needed
> 
> > __WD_Post ==> Success (0) HTTP status = 200 :
> > Who matters about RESPONSE text in LOG when Success was taken ?
> 
> There may be instances where seeing the full response would be beneficial even if the function call was successful. For example, what if there was a bug in __WD_DetectError where it failed to detect an error? In this case, it would return $_WD_ERROR_Success and seeing the actual response text could help with isolating the issue.
> 

I hope my code posted few minutes ago (an answer above) shows that this will be solved.


> > If somebody cares then he should put it to LOG on his own.
> 
> How would they do that if it isn't being returned by the function?

currently there is only
```autoit
Global $_WD_HTTPRESULT = 0 ; Result of last WinHTTP request
```

I propose to add
```autoit
Global $_WD_RESPONSETEXT = "" ; Response text of last WinHTTP request
```

> 
> > HTTP status = 200
> 
> I think we previously discussed dropping "HTTP status = xxx" from the logging output. What is your recollection of that discussion?

**I must back to this and rethinking.**

**Comment by Danp2** [comment]
> Internal ? You mean __WD_Post/Get/Delete ?

Yes, and any other internal function of the UDF where there is currently a call to __WD_ConsoleWrite().

>I have in the background this modification
>Is this what you was thinking about ?

That would still result in logging of internal functions when WD_DEBUG <= $_WD_DEBUG_Info, right?

I was thinking that this output would be completely eliminated. This thought of changing __WD_Efrror just popped into my head. Something like this --

```autoit
Func __WD_Error($sWhere, $iErr, $sMessage = Default, $iExt = Default)
	Local Const $sFuncName = "__WD_Error"
	Local $sMsg

	If $sMessage = Default Then $sMessage = ''

	If $_WD_DEBUG = $_WD_DEBUG_Full Or Left($sWhere, 2) <> '__' Then
		; Existing Switch code goes here
	Endif

	Return $iErr
EndFunc   ;==>__WD_Error
```

There may be better ways to implement this, so feel free to suggest alternatives.

**Comment by Danp2** [comment]
> Global $_WD_HTTPRESPONSE

I'll have to think about that one for a bit

**Comment by mlipok** [comment]
I would like to propose this kind of `__WD_Error()` behavior/way to operate:

**Case `$_WD_DEBUG_None`** 
do not send any message to the console even errors

**Case `$_WD_DEBUG_Error`**  "only when error occurs"

this following should be used
```autoit
Local $sExtended = (($iExt <> Default) ? (" / " & $iExt) : (""))
$sMsg = $sWhere & " ==> " & $aWD_ERROR_DESC[$iErr] & " (" & $iErr & $sExtended & ")"
$sMsg &= (($sMessage) ? (" : " & $sMessage) : (""))
```

but this part:
```autoit
If $iExt = Default Then $sMsg &= (($_WD_HTTPRESULT) ? (" HTTP status = " & $_WD_HTTPRESULT) : ("")) ; _WD_LastHTTPResult()
```

should be moved out of `__WD_Error()`
And should be only used by passing messages as a parameter to the `__WD_Error()`  **but only from `__WD_Post/Get/Delete`**

I mean functions like `_WD_Wait...`  and `_WD_Find....` and any one `_WD_****`  else than `__WD_Post/Get/Delete` should not pass again message about HTTP status as only `__WD_Post/Get/Delete` should do this to not duplicate the same information.


**Case `$_WD_DEBUG_Info`**

Trimmed `$sResponseText` should be passed from `__WD_Post/Get/Delete` 

**REMARK:** Response text should not be passed to console by any other function.

**Case `$_WD_DEBUG_Full`**

Full `$sResponseText` should be passed from `__WD_Post/Get/Delete` 

**REMARK:** Response text should not be passed to console by any other function.

example:
```autoit
	__WD_ConsoleWrite($sFuncName & ": URL=" & $sURL & "; $sData=" & $sData, $_WD_DEBUG_Info)
	Local $sMessage = (($iResult And $_WD_DEBUG = $_WD_DEBUG_Info) ? ("ResponseText=" & StringLeft($sResponse, $_WD_RESPONSE_TRIM) & "...") : (""))
	$sMessage = (($_WD_DEBUG = $_WD_DEBUG_Full) ? ("ResponseText=" & $sResponseText) : (""))
	Return SetError(__WD_Error($sFuncName, $iResult, $sMessage), 0, $sResponseText)
EndFunc   ;==>__WD_Post
```

**REMARK**
This following part should work without any changes
```autoit
			If $iErr <> $_WD_ERROR_Success Then
				If $_WD_ERROR_MSGBOX Then
					Local $iAnswer = MsgBox($MB_ICONERROR + $MB_OKCANCEL + $MB_TOPMOST, "WebDriver UDF Error:", $sMsg)
					If $iAnswer = $IDCANCEL Then
						$iErr = $_WD_ERROR_UserAbort ; change $iErr to give a way to stop further processing by user interaction
						__WD_ConsoleWrite($sFuncName & ": User Abort", $_WD_DEBUG_Info)
					EndIf
				EndIf
				If $_WD_ERROR_OUTPUTDEBUG Then
					DllCall("kernel32.dll", "none", "OutputDebugString", "str", $sMsg)
				EndIf
			EndIf
```


**REMARK:** About __WD_ConsoleWrite() usage 
I mean this kind:
```autoit
	__WD_ConsoleWrite($sFuncName & ": URL=" & $sURL & "; $sData=" & $sData, $_WD_DEBUG_Info)
```
or
```autoit
	__WD_ConsoleWrite($sFuncName & ': #' & @ScriptLineNumber & ' : > ' & Json_Encode($_WD_CAPS__OBJECT) & ' > IsObj = ' & IsObj($_WD_CAPS__OBJECT), $_WD_DEBUG_Full)
```

this should not be changed.

**Comment by mlipok** [comment]
> > Global $_WD_HTTPRESPONSE
> 
> I'll have to think about that one for a bit

I just focused on:
```autoit
$_WD_SESSION_DETAILS = $sResponse
```

Should we remove `$_WD_SESSION_DETAILS` and  add `$_WD_HTTPRESPONSE` for all `__WD_Post/Get/Delete` ?

**Comment by Danp2** [comment]
> Should we remove $_WD_SESSION_DETAILS

This global variable is currently used by _WD_GetSession

> Case $_WD_DEBUG_Info
>
> Trimmed $sResponseText should be passed from __WD_Post/Get/Delete

Not sure about this. My idea was to completely remove these lines unless $_WD_DEBUG_Full was in use.

**Comment by mlipok** [comment]
Please take a look on recent changes in:
https://github.com/Danp2/au3WebDriver/pull/290

they are related to this comment: https://github.com/Danp2/au3WebDriver/issues/280#issuecomment-1099580099

**Comment by mlipok** [comment]
Can we close this issue ?
And only continue in https://github.com/Danp2/au3WebDriver/pull/290 ?
