### ISSUE TITLE
$_WD_KEYS__*** renaming and comments

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#284]
### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

fit JSON.au3 naming and comments

```autoit
#TODO $_WD_KEYS__STANDARD ; should be split to $_WD_KEYS__STANDARD_PRIMITIVE and $_WD_KEYS__STANDARD_STRING and comments should be suplemented - to fit JSON.au3 conventions/naming
Global $_WD_KEYS__STANDARD = _ ; this should be RegExpPattern
		'(?i)\A(acceptInsecureCerts|browserName|browserVersion|platformName|pageLoadStrategy|setWindowRect|strictFileInteractability|unhandledPromptBehavior)\Z'

Global $_WD_KEYS__STANDARD_OBJECT = _ ; this should be RegExpPattern of - "JSON_OBJECT" - "a dictionary element" that should be placed in STANDARD part of Capabilities JSON structure
		'(?i)\A(proxy|timeouts)\Z'

Global $_WD_KEYS__STANDARD_OBJECT_ARRAY = _ ; this should be RegExpPattern of - "JSON_ARRAY" - "a list of element" that should be placed in "dicionary element" in STANDARD part of Capabilities JSON structure
		'(?i)\A(noproxy)\Z'

Global $_WD_KEYS__SPECIFICVENDOR_STRING = _ ; this should be RegExpPattern of - "JSON_STRING" - "a string element" that should be placed in SPECIFICVENDOR part of Capabilities JSON structure
		'(?i)\A(binary|debuggerAddress|minidumpPath)\Z'

#TODO $_WD_KEYS__SPECIFICVENDOR_BOOLEAN ; should be renamed to $_WD_KEYS__SPECIFICVENDOR_PRIMITIVE - to fit JSON.au3 conventions/naming
Global $_WD_KEYS__SPECIFICVENDOR_BOOLEAN = _ ; this should be RegExpPattern of - "JSON_PRIMITIVE" - "a primitive element" that should be placed in SPECIFICVENDOR part of Capabilities JSON structure
		'(?i)\A(w3c|detach)\Z'

Global $_WD_KEYS__SPECIFICVENDOR_ARRAY = _ ; this should be RegExpPattern of - "JSON_ARRAY" - "a list of element" that should be placed in SPECIFICVENDOR part of Capabilities JSON structure
		'(?i)\A(args|extensions|excludeSwitches|windowTypes)\Z'

Global $_WD_KEYS__SPECIFICVENDOR_OBJECT = _ ; this should be RegExpPattern of - "JSON_OBJECT" - "a dictionary element" that should be placed in SPECIFICVENDOR part of Capabilities JSON structure
		'(?i)\A(env|log|prefs|perfLoggingPrefs|mobileEmulation|localState)\Z'


```

### Describe alternatives you've considered

none

### Additional context

The comments I have already changed in one of my WIP script it will be published as PR soon.

I need change `$_WD_KEYS__SPECIFICVENDOR_BOOLEAN` >> `$_WD_KEYS__SPECIFICVENDOR_PRIMITIVE`

And also split `$_WD_KEYS__STANDARD` into `$_WD_KEYS__STANDARD_PRIMITIVE` and `$_WD_KEYS__STANDARD_STRING`

And this second thing will be little more diffucultly, for this reason I create this as `ISSUE`.

btw.
@Danp2  please assign this ISSUE to me.

**Comment by mlipok** [comment]
> I need change `$_WD_KEYS__SPECIFICVENDOR_BOOLEAN` >> `$_WD_KEYS__SPECIFICVENDOR_PRIMITIVE`

For this I still wondering if it is needed.

**Comment by Danp2** [comment]
Good idea to discuss this further before submitting the PR.

> For this I still wondering if it is needed.

Agreed. 

> I need change $_WD_KEYS__SPECIFICVENDOR_BOOLEAN >> $_WD_KEYS__SPECIFICVENDOR_PRIMITIVE

Why? It's simply a variable name, which doesn't need to match anything coming from JSON UDF in my opinion. Are you just being nit-picky or is there a valid reason for making this change? 🤔

**Comment by mlipok** [comment]
I just do this:
```autoit
conventions/naming
Global $_WD_KEYS__SPECIFICVENDOR_BOOLEAN = _ ; this should be RegExpPattern of - "JSON_PRIMITIVE" - "a primitive element" that should be placed in SPECIFICVENDOR part of Capabilities JSON structure
		'(?i)\A(w3c|detach)\Z'
```
I mean I do not change variable name `$_WD_KEYS__SPECIFICVENDOR_BOOLEAN`

but I stick with this comment `"JSON_PRIMITIVE" - "a primitive element"`

**Comment by mlipok** [comment]
What about:
`#TODO $_WD_KEYS__STANDARD ; should be split to $_WD_KEYS__STANDARD_PRIMITIVE and $_WD_KEYS__STANDARD_STRING and comments should be suplemented - to fit JSON.au3 conventions/naming`

I think that then I would be also able to do better `@error` handling.

**Comment by Danp2** [comment]
> I mean I do not change variable name $_WD_KEYS__SPECIFICVENDOR_BOOLEAN

Ok, but that isn't what I originally understood you to say. 🙁 

> ; this should be RegExpPattern of - "JSON_PRIMITIVE" - "a primitive element" that should be placed in SPECIFICVENDOR part of Capabilities JSON structure

So you simple want to expand the comment associated with the variable $_WD_KEYS__SPECIFICVENDOR_BOOLEAN?

FWIW, I don't see this as an improvement because `Json_PRIMITIVE` appears to include all variable types, including numbers and strings.

> What about:
#TODO $_WD_KEYS__STANDARD

Let us hold off on answering this until we've resolve the above.

**Comment by mlipok** [comment]
> > I mean I do not change variable name $_WD_KEYS__SPECIFICVENDOR_BOOLEAN
> 
> Ok, but that isn't what I originally understood you to say. 🙁

Give me a way to say it again little refactored ;)
`.............................................................................`

> > For this I still wondering if it is needed.
> 
> Agreed.
> 
> > I need change $_WD_KEYS__SPECIFICVENDOR_BOOLEAN >> $_WD_KEYS__SPECIFICVENDOR_PRIMITIVE
> 
> Why? It's simply a variable name, which doesn't need to match anything coming from JSON UDF in my opinion. Are you just being nit-picky or is there a valid reason for making this change? 🤔



Ok. I can agree tha this is not needed.

So I just do this:
```autoit
Global $_WD_KEYS__SPECIFICVENDOR_BOOLEAN = _ ; this should be RegExpPattern of - "JSON_PRIMITIVE" - "a primitive element" that should be placed in SPECIFICVENDOR part of Capabilities JSON structure
		'(?i)\A(w3c|detach)\Z'
```
I mean I plan to not change variable name `$_WD_KEYS__SPECIFICVENDOR_BOOLEAN`

but I stick with this comment `"JSON_PRIMITIVE" - "a primitive element"`

**Comment by mlipok** [comment]
> So you simple want to expand the comment associated with the variable $_WD_KEYS__SPECIFICVENDOR_BOOLEAN?

Exactly.

**Comment by mlipok** [comment]
> FWIW, I don't see this as an improvement because `Json_PRIMITIVE` appears to include all variable types, including numbers and strings.

not strings as there is separate `Case 3 ; JSON_STRING`

```autoit
Func _Json_Token(ByRef $Json, $Ptr, ByRef $Next)
	If $Next = -1 Then Return Null

	Local $Token = DllStructCreate("int;int;int;int", $Ptr + ($Next * 20))
	Local $Type = DllStructGetData($Token, 1)
	Local $Start = DllStructGetData($Token, 2)
	Local $End = DllStructGetData($Token, 3)
	Local $Size = DllStructGetData($Token, 4)
	$Next += 1

	If $Type = 0 And $Start = 0 And $End = 0 And $Size = 0 Then ; Null Item
		$Next = -1
		Return Null
	EndIf

	Switch $Type
		Case 0 ; JSON_PRIMITIVE - a permitive element in JSON structure
			Local $Primitive = StringMid($Json, $Start + 1, $End - $Start)
			Switch $Primitive
				Case "true"
					Return True
				Case "false"
					Return False
				Case "null"
					Return Null
				Case Else
					If StringRegExp($Primitive, "^[+\-0-9]") Then
						Return Number($Primitive)
					Else
						Return Json_StringDecode($Primitive)
					EndIf
			EndSwitch

		Case 1 ; JSON_OBJECT - a dicionary element in JSON structure
			Local $Object = Json_ObjCreate()
			For $i = 0 To $Size - 1 Step 2
				Local $Key = _Json_Token($Json, $Ptr, $Next)
				Local $Value = _Json_Token($Json, $Ptr, $Next)
				If Not IsString($Key) Then $Key = Json_Encode($Key)

				If $Object.Exists($Key) Then $Object.Remove($Key)
				$Object.Add($Key, $Value)
			Next
			Return $Object

		Case 2 ; JSON_ARRAY - a list of elements in JSON structure
			Local $Array[$Size]
			For $i = 0 To $Size - 1
				$Array[$i] = _Json_Token($Json, $Ptr, $Next)
			Next
			Return $Array

		Case 3 ; JSON_STRING - a string element in JSON structure
			Return Json_StringDecode(StringMid($Json, $Start + 1, $End - $Start))
	EndSwitch
EndFunc   ;==>_Json_Token

```

**Comment by Danp2** [comment]
> Give me a way to say it again little refactored ;)

>    I need change $_WD_KEYS__SPECIFICVENDOR_BOOLEAN >> $_WD_KEYS__SPECIFICVENDOR_PRIMITIVE

To me, the above is you stating that you want to rename the variable. You also put this in the code --

`#TODO $_WD_KEYS__SPECIFICVENDOR_BOOLEAN ; should be renamed to $_WD_KEYS__SPECIFICVENDOR_PRIMITIVE - to fit JSON.au3 conventions/naming`

So it seems that your original intent was to rename the variable. 😦 

> no..... not strings, as there is separate Case 3 ; JSON_STRING

One of us has misinterpreted the code, but I'm not sure if it was you or me. I simply looked at the code under `Case 0 ; Json_PRIMITIVE` and could see where it was dealing with boolean, null, numbers, and then strings as a default. 🤷‍♂️

**Comment by mlipok** [comment]
> > Give me a way to say it again little refactored ;)
> 
> > I need change $_WD_KEYS__SPECIFICVENDOR_BOOLEAN >> $_WD_KEYS__SPECIFICVENDOR_PRIMITIVE
> 
> To me, the above is you stating that you want to rename the variable. You also put this in the code --
> 
> `#TODO $_WD_KEYS__SPECIFICVENDOR_BOOLEAN ; should be renamed to $_WD_KEYS__SPECIFICVENDOR_PRIMITIVE - to fit JSON.au3 conventions/naming`
> 
> So it seems that your original intent was to rename the variable. 😦
> 
> > no..... not strings, as there is separate Case 3 ; JSON_STRING
> 
> One of us has misinterpreted the code, but I'm not sure if it was you or me. I simply looked at the code under `Case 0 ; Json_PRIMITIVE` and could see where it was dealing with boolean, null, numbers, and then strings as a default. 🤷‍♂️

Quite possible me.
As I do not do all the test I hope to do, and only I keep it in my mind ;)

**Comment by Danp2** [comment]
Let me know when you figure it out. 😆 AFAICS, there's nothing that needs to be done here.

**Comment by mlipok** [comment]
Here is interesting article:
[Primitive and compound JSON data types](https://docs.yugabyte.com/preview/api/ysql/datatypes/type_json/primitive-and-compound-data-types/)

Please take a look also on:
https://w3c.github.io/webdriver/#dfn-script-timeout

<html>
<body>


Field | Default | JSON key | Optional† | Nullable | Description†
-- | -- | -- | -- | -- | --
Script timeout | 30,000 | "script" | ✓ | ✓ | Specifies when to interrupt a script that is being evaluated.A null value implies that scripts should never be interrupted, but instead run indefinitely.


This value is `Nullable` so we can't validate all the parameters.

**Comment by Danp2** [comment]
> So we can't validate all the parameters.

I'm not sure that I understand the issue. Which parameters need validation? 

The addition of wd_capabilities to this project provides some "utility" functions to assist the user in building a Capabilities string. However, I don't believe these functions should be expected to enforce the w3c standards. That's the job of whichever webdriver is being used.

**Comment by mlipok** [comment]
> However, I don't believe these functions should be expected to enforce the w3c standards. That's the job of whichever webdriver is being used.

Agree.

**Comment by mlipok** [comment]
Take a look on: [$_WD_CAPS__API and _WD_CapabilitiesDisplay - removed](https://github.com/Danp2/au3WebDriver/pull/285)
There are related changes.
