### ISSUE TITLE
Capabilities $_WD_KEYS__***` should RegExp be case sensitive or insensitive ?

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#286]
@mlipok 
Wondering if RegExp should be case sensitive or insensitive?

@danp2
> I would suggest insensitive unless that will lead to invalid or rejected Capabilities strings

@mlipok 
> Using FifreFox check 'pageload' instead 'pageLoad'

EXAMPLE:

Current:
```autoit
Global $_WD_KEYS__SPECIFICVENDOR_PRIMITIVE = _
	'(?i)\A(binary|debuggerAddress|detach|minidumpPath|w3c)\Z'
```

Proposal:
```autoit
Global $_WD_KEYS__SPECIFICVENDOR_PRIMITIVE = _
	'\A(binary|debuggerAddress|detach|minidumpPath|w3c)\Z'
```

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/pull/285#discussion_r846531876_

**Comment by Danp2** [comment]
Needs to be changed. Should be addressed in existing PR.
