### ISSUE TITLE
Feature Request:   new global value $_WD_HTTPRESPONSE - last HTTP response

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#294]
> > Global $_WD_HTTPRESPONSE
> 
> I'll have to think about that one for a bit

I just focused on:
```autoit
$_WD_SESSION_DETAILS = $sResponse
```

Should we remove `$_WD_SESSION_DETAILS` and  add `$_WD_HTTPRESPONSE` for all `__WD_Post/Get/Delete` ?

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/issues/280#issuecomment-1099983239_

**Comment by Danp2** [comment]
Answered in original issue

**Comment by mlipok** [comment]
Thanks for answer about removing  `$_WD_SESSION_DETAILS`

What about staying in this issue to talko about: add `$_WD_HTTPRESPONSE` for all `__WD_Post/Get/Delete` ?
and your previous response:



> > > > If somebody cares then he should put it to LOG on his own.
> > > 
> > > How would they do that if it isn't being returned by the function?
> > 
> > currently there is only
> > 
> > ```autoit
> > Global $_WD_HTTPRESULT = 0 ; Result of last WinHTTP request
> > ```
> > 
> > I propose to add
> > 
> > ```autoit
> > Global $_WD_HTTPRESPONSE = "" ; Response text of last WinHTTP request
> > ```
> I'll have to think about that one for a bit

from here:
https://github.com/Danp2/au3WebDriver/issues/280#issuecomment-1099329426

**Comment by Danp2** [comment]
I'm ok with this change. You'll also need to add the function _WD_LastHTTPResponse.

**Comment by mlipok** [comment]
Ok.
But first we must focus on almost all current PRs (GDPR can wait longer).
