### ISSUE TITLE
_WD_GetBrowserPath() does not return the full path

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#306]
### How to reproduce

```autoit
_WD_GetBrowserPath('firefox')
```
returns "FIREFOX.EXE" instead true/full path.

```[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe]
@="FIREFOX.EXE"
"Path"=""
```

### Expected behavior

To be rethinking what to do.

### Screenshots

![image](https://user-images.githubusercontent.com/11089482/167116784-7bca7fc7-e8ee-4982-b127-450803ae7683.png)

![image](https://user-images.githubusercontent.com/11089482/167116808-aac87aa7-6abd-42a9-b6f9-b6d8447ec477.png)

### Additional context

None

### System under test

Please complete the following information.

- Browser FireFox 
- Browser version 100.0 64Bit

https://www.mozilla.org/en-US/firefox/100.0/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-desktop&utm_campaign=about-dialog

**Comment by Danp2** [comment]
For some reason your registry isn't correct. Here's what I get --

```
@="C:\\Program Files\\Mozilla Firefox\\firefox.exe"
"Path"="C:\\Program Files\\Mozilla Firefox"
```

Since the function is designed to retrieve the registry settings, I'm not sure how you would propose to "fix" something that isn't broken. 😃 

Have you tested this with other browsers? If so, what was the result?

**Comment by mlipok** [comment]
I solve this with this code:
```autoit
If $s_FireFox_Binary = Default Then $s_FireFox_Binary = _WD_GetBrowserPath('firefox')
If Not FileExists($s_FireFox_Binary) Then
	If FileExists(@LocalAppDataDir & "\Mozilla Firefox\firefox.exe") Then
		$s_FireFox_Binary = @LocalAppDataDir & "\Mozilla Firefox\firefox.exe"
	EndIf
EndIf
```

I think there is a need to check if file exist, and in case of not existen file returned by `_WD_GetBrowserPath` there should be `$_WD_ERROR_FileIssue` set as `@error`

**Comment by mlipok** [comment]
also we can add `If FileExists(@LocalAppDataDir & "\Mozilla Firefox\firefox.exe") Then` as an additionall check in case when registry entries doesnt point you to existen file.

**Comment by Danp2** [comment]
A few suggestions if you decide to expand the functionality of _WD_GetBrowserPath --

- Expand `$_WD_SupportedBrowsers` to hold these predefined locations
- Update the description in the header to include "predefined locations on disk"
- Check the error codes in the header for accuracy

**Comment by mlipok** [comment]
I notice that my Chome is located:
`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`

As I have Chrome 64bit version I start to wonder why this is not `C:\Program Files\Google\Chrome\Application\chrome.exe`

**Comment by mlipok** [comment]
So we should not look everywhere.
But do we should check if the path exist ?

**Comment by Danp2** [comment]
> But should we check if the path exists?

I don't believe this is needed. If you do decide to add this, then be sure that it doesn't change the existing functionality (ie: you can set an error code, but the registry path should still be returned).

**Comment by mlipok** [comment]
I will add `$_WD_ERROR_FileIssue` but I will follow you recomendation:

> then be sure that it doesn't change the existing functionality (ie: you can set an error code, but the registry path should still be returned).

I am temporarily holding back, however, in order to finish my current PR and stabilize the version I'm working on.

**Comment by mlipok** [comment]
I plan to take a look on this in next few days

**Comment by mlipok** [comment]
> If you do decide to add this, then be sure that it doesn't change the existing functionality (ie: you can set an error code, but the registry path should still be returned).

I will add feaure which will set additionall ERRROR only in case when the registry entries is empty string, as in my screenshot and of course it will return this exact empty string.
Is it fine for you ?

**Comment by Danp2** [comment]
That should be fine. However, it isn't clear if you intend to use @error or @extended to indicate this additional error. I would suggest using @extended.

**Comment by mlipok** [comment]
IMHO if the registry had an empty string as the path, then it should be marked as **@error** as the user expects that on success you will get a valid path.

**Comment by Danp2** [comment]
To clarify my earlier statement, I was trying to suggest that you use one of the existing error codes (ie: $_WD_ERROR_NotFound) along with a unique value in @extended to indicate that the registry key was empty.

**Comment by mlipok** [comment]
You can assign this to me.

**Comment by Danp2** [comment]
Closing this for now as the current implementation is performing as originally designed.
