### ISSUE TITLE
_WD_Startup() - FireFox not responding

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#308]
### Describe the bug

_WD_Startup() runs well but FireFox was not responding.
Thus entire program goes forward and further _WD_WaitElement() fired TIMEOUT error.

### How to reproduce

Try to run session with FireFox on case when previous session not ended well.

### Expected behavior

_WD_Startup() should be able to fire error in case process is not responding.
To be rethinking.

### Screenshots

![image](https://user-images.githubusercontent.com/11089482/167599957-992f62fa-5762-43e8-a7ae-42a1ac1a020f.png)

"By hand" translation:
"Firefox has already started, but not respond. To open new window you need firstly close old FireFox process."
"Close Firefox program"
"Cancel"

### Additional context

None

### System under test

Please complete the following information.

- Browser firefox

**Comment by Danp2** [comment]
Is this reproducible? Do you have a copy of the logs from when this occurred?

**Comment by mlipok** [comment]
> Is this reproducible? Do you have a copy of the logs from when this occurred?

Will try to reproduce.

**Comment by mlipok** [comment]
Here I found some resources:
https://support.mozilla.org/en-US/kb/firefox-wont-start-find-solutions

specifically:
https://support.mozilla.org/en-US/kb/firefox-already-running-not-responding
![2014-11-11-04-50-05-369346 1](https://user-images.githubusercontent.com/11089482/170556795-06d24466-8e68-4146-96e5-dee0261cef37.png)

**Comment by Danp2** [comment]
This seems to be an environmental issue rather than a webdriver issue. It may not be appropriate to apply a "fix" to this UDF. It will be difficult to know without the ability to reproduce it and obtain logs.

**Comment by mlipok** [comment]
I'm extreamly busy with my projects (migrating from IE to WD)
So I only notice issues on github as far as I notice them and have some spare time to notice........ and I will back to them ASAP.

Will try to make repro script ASAP , for this issue I think that I can mark deadline to this weekend.

**Comment by mlipok** [comment]
I had a flash of invention.
Here is repro script:
[wd_demo_MOD.zip](https://github.com/Danp2/au3WebDriver/files/8782115/wd_demo_MOD.zip)



```
1653598888988   geckodriver     INFO    Listening on 127.0.0.1:4444
1653598890110   webdriver::server       DEBUG   -> POST /session {
    "capabilities":{
        "alwaysMatch":{
            "browserName":"firefox",
            "acceptInsecureCerts":true,
            "moz:firefoxOptions":{
                "args":[
                    "-profile",
                    "C:\\Users\\agatk\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\WD_Testing_Profile"
                ]
            }
        }
    }
}
1653598890122   geckodriver::browser    DEBUG   Backing up prefs to "C:\\Users\\agatk\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\WD_Testing_Profile\\user.geckodriver_backup_163"
1653598890132   mozrunner::runner       INFO    Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "--marionette" "-profile" "C:\\Users\\agatk\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\WD_Testing_Profile" "-no-remote"
1653598890137   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:57580
1653598892173   geckodriver::marionette TRACE   Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia. (os error 10061). Retrying in 100ms
1653598894328   geckodriver::marionette TRACE   Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia. (os error 10061). Retrying in 100ms
1653598896463   geckodriver::marionette TRACE   Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia. (os error 10061). Retrying in 100ms
.....
.....
.....
.....
````

![image](https://user-images.githubusercontent.com/11089482/170579760-4caf9b5f-c44b-4998-80e0-fe572116ae74.png)

**Comment by mlipok** [comment]
Just try to run [wd_demo_MOD.zip](https://github.com/Danp2/au3WebDriver/files/8782115/wd_demo_MOD.zip) twice.
You do not need to do any change in the setting.

**Comment by Danp2** [comment]
You are attempting to access the same user profile from two different instances of Firefox, which isn't allowed.

**Comment by mlipok** [comment]
Oh....
https://support.mozilla.org/en-US/kb/firefox-already-running-not-responding

I find out how to fix :

```autoit
	#Region - mLipok testing
	Local $s_Browser_Profile_Dir = _WD_ProfileDir('firefox')
	Local $s_ProfileLock = $s_Browser_Profile_Dir & '\parent.lock'
	FileDelete($s_ProfileLock)
	If FileExists($s_ProfileLock) Then
		ConsoleWrite("! PROFILE IS LOCKED: " & $s_ProfileLock & @CRLF)
		Exit
	EndIf
	_WD_CapabilitiesAdd('args', '-profile')
	_WD_CapabilitiesAdd('args', $s_Browser_Profile_Dir) ; CHANGE TO PROPER DIRECTORY PATH
	#EndRegion - mLipok testing
```

**Comment by Danp2** [comment]
Glad you found a reliable way to detect that the profile is locked.

**Comment by mlipok** [comment]
Wondering how to do the same with Chrome

**Comment by Danp2** [comment]
use `lockfile` instead of `parent.lock`

**Comment by mlipok** [comment]
Hmm ... looks like Chrome doesn't have this problem - you can run multiple instances.

**Comment by mlipok** [comment]
> use `lockfile` instead of `parent.lock`

this works:
```autoit
	#Region - mLipok testing
	Local $s_Browser_Profile_Dir = _WD_ProfileDir('chrome')
	Local $s_ProfileLock = $s_Browser_Profile_Dir & '\lockfile'
	FileDelete($s_ProfileLock)
	If FileExists($s_ProfileLock) Then
		ConsoleWrite("! PROFILE IS LOCKED: " & $s_ProfileLock & @CRLF)
		Exit
	EndIf
	_WD_CapabilitiesAdd('args', 'user-data-dir', $s_Browser_Profile_Dir)
	_WD_CapabilitiesAdd('args', '--profile-directory', Default)
	#EndRegion - mLipok testing
```

**Comment by mlipok** [comment]
This kind of checking could be performed only when user want to create new session and trying to attach.

My finall version of testing script is below:
[wd_demo_MOD.zip](https://github.com/Danp2/au3WebDriver/files/8782737/wd_demo_MOD.zip)
