### ISSUE TITLE
wd_demo.au3 - windows 11 indistinguishable buttons status

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#311]
### Describe the bug

Using Windows 11 graphical differences for selected / deselcted buttons is almost indistinguishable

### How to reproduce

on Windows 11
1. Run wd_demo.au3
2. select and deselect few `Demos`
3. you will notice that the graphical differences for selected / deselcted buttons is almost indistinguishable

### Expected behavior

to clearly see which button / demo is pressed.

### Screenshots

![image](https://user-images.githubusercontent.com/11089482/170578240-6c78e755-25e3-4e6c-9bc3-b701724338f1.png)

### Additional context

none

### System under test

Windows 11

**Comment by Danp2** [comment]
I recently noticed this issue as well.

**Comment by Danp2** [comment]
Any ideas on how to fix this?

**Comment by mlipok** [comment]
> Any ideas on how to fix this?

Not yet

**Comment by Danp2** [comment]
From [here](https://docs.microsoft.com/en-us/windows/win32/controls/wm-ctlcolorbtn#remarks) --

> By default, the [DefWindowProc](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-defwindowproca) function selects the default system colors for the button. Buttons with the [BS_PUSHBUTTON](https://docs.microsoft.com/en-us/windows/win32/controls/button-styles), [BS_DEFPUSHBUTTON](https://docs.microsoft.com/en-us/windows/win32/controls/button-styles), or [BS_PUSHLIKE](https://docs.microsoft.com/en-us/windows/win32/controls/button-styles) styles do not use the returned brush. Buttons with these styles are always drawn with the default system colors. Drawing push buttons requires several different brushes-face, highlight, and shadow-but the WM_CTLCOLORBTN message allows only one brush to be returned. To provide a custom appearance for push buttons, use an owner-drawn button. For more information, see [Creating Owner-Drawn Controls](https://docs.microsoft.com/en-us/windows/win32/controls/user-controls-intro).

Sounds like we will need to subclass the controls and manage the background color ourselves.

**Comment by mlipok** [comment]
It is fixed in yours PR
