### ISSUE TITLE
$_WD_DRIVER_CLOSE - description / usage

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#328]
### Describe the bug
comment for `$_WD_DRIVER_CLOSE` says:
```autoit
Global $_WD_DRIVER_CLOSE = True ; Close prior driver instances before launching new one
```
function header for `__WD_CloseDriver` says:
```
; Description ...: Shutdown web driver console if it exists.
```

also `parameters` are sugesting that we should put there name or PID of `conhost.exe` instead the name or PID of WebDriver

```
; Parameters ....: $vDriver - [optional] The name or PID of Web driver console to shutdown. Default is $_WD_DRIVER
```

Other question is why __WD_CloseDriver() does not close the browser?

### How to reproduce

just take a look on code, comments, descriptions.

### Expected behavior

more consistent and accurate documentation

### Screenshots

none

### Additional context

none

### System under test

none

**Comment by Danp2** [comment]
I suppose this could be revised to make it clearer. The function `_WD_ConsoleVisible` complicates things. 

> Global $_WD_DRIVER_CLOSE = True ; Close prior driver instances before launching new one

I see no issues here.

> ; Description ...: Shutdown web driver console if it exists.
> ; Parameters ....: $vDriver - [optional] The name or PID of Web driver console to shutdown. Default is $_WD_DRIVER

The word `console` could be removed from these comments to avoid any potential confusion.

FWIW, I'm unaware of anyone else jumping to the conclusion that `web driver console` referred to `conhost.exe`. The webdrivers are console applications after all, correct?

**Comment by mlipok** [comment]
> > Global $_WD_DRIVER_CLOSE = True ; Close prior driver instances before launching new one
> 
> I see no issues here.

but compare it with function header for __WD_CloseDriver says:

`; Description ...: Shutdown web driver console if it exists.`

btw.

You already answered here:
> The word `console` could be removed from these comments to avoid any potential confusion.

**Comment by mlipok** [comment]
> Other question is why __WD_CloseDriver() does not close the browser?

What about this question ?

**Comment by mlipok** [comment]
I have no more question here.
You can close it.
