### ISSUE TITLE
_WD_HTTPRESULT is returning wrong code

### ISSUE THREAD

**Issue by vigri** [Danp2/au3WebDriver#341]
### Describe the bug

_WD_HTTPRESULT is returning always `200` instead of the "real" status code.

### How to reproduce

Minimum code that produces the error

#### 404-test.au3
```
#include "wd_helper.au3"
#include "wd_capabilities.au3"

Func SetupGecko($bHeadless)
	_WD_Option('Driver', 'geckodriver.exe')
	_WD_Option('DriverParams', '--log trace')
	_WD_Option('Port', 4444)

	_WD_CapabilitiesStartup()
	_WD_CapabilitiesAdd('alwaysMatch', 'firefox')
	_WD_CapabilitiesAdd('browserName', 'firefox')
	_WD_CapabilitiesAdd('acceptInsecureCerts', True)
	If $bHeadless Then _WD_CapabilitiesAdd('args', '--headless')
	_WD_CapabilitiesDump(@ScriptLineNumber) ; dump current Capabilities setting to console - only for testing in this demo
	Local $sCapabilities = _WD_CapabilitiesGet()
	Return $sCapabilities
EndFunc   ;==>SetupGecko

Local $url = '192.168.0.7/404.php'
Local $bHeadless = False
Local $sCapabilities = SetupGecko($bHeadless)
Local $iWebDriver_PID = _WD_Startup()
Local $sSession = _WD_CreateSession($sCapabilities)

If @error <> $_WD_ERROR_Success Then
	ConsoleWrite("Session not created..." & @error)
	Exit
EndIf

_WD_Navigate($sSession, $url)
_WD_LoadWait($sSession)

ConsoleWrite("HTTP status: " & $_WD_HTTPRESULT)
```

#### 404.php
```
<?php
header("HTTP/1.0 404 Not Found");
```

### Expected behavior

The http status code - and therefore `_WD_HTTPRESULT` should return `404`. Instead a `200` is returned - no matter what the real http response was.

##### Postman
![postman-404](https://user-images.githubusercontent.com/2580723/180245995-3662a62b-c212-4597-837d-e279c40ae0b2.png)

##### Firefox
![ff-404](https://user-images.githubusercontent.com/2580723/180246041-544deee6-1cb8-4772-b088-7f6245668976.png)

##### Console (SciTE)
```
_WD_Option ==> Success [0] : Parameters:   Option=Driver   Value=geckodriver.exe
_WD_Option ==> Success [0] : Parameters:   Option=DriverParams   Value=--log trace
_WD_Option ==> Success [0] : Parameters:   Option=Port   Value=4444
_WD_CapabilitiesAdd ==> Success [0] : Successfully used [alwaysMatch]  with specified browser: firefox
_WD_CapabilitiesAdd ==> Success [0] : Successfully added capability
_WD_CapabilitiesAdd ==> Success [0] : Successfully added capability
_WD_CapabilitiesDump: JSON structure starts below: 14
{
    "capabilities":{
        "alwaysMatch":{
            "browserName":"firefox",
            "acceptInsecureCerts":true
        }
    }
}
_WD_CapabilitiesDump: JSON structure ends above.
_WD_IsLatestRelease ==> Success [0] : True
_WD_Startup: OS:	WIN_10 WIN32_NT 19044 
_WD_Startup: AutoIt:	3.3.16.0
_WD_Startup: Webdriver UDF:	0.10.0 (Up to date)
_WD_Startup: WinHTTP:	1.6.4.1 (Download latest source at <https://raw.githubusercontent.com/dragana-r/autoit-winhttp/master/WinHttp.au3>)
_WD_Startup: Driver:	geckodriver.exe (64 Bit)
_WD_Startup: Params:	--log trace
_WD_Startup: Port:	4444
_WD_Startup: Command:	"geckodriver.exe" --log trace 
_WD_Startup ==> Success [0]
__WD_Post ==> Success [0] : HTTP status = 200
_WD_CreateSession ==> Success [0] : d41abbba-2dde-4ca9-99ac-5f2f9f381ad5
__WD_Post ==> Success [0] : HTTP status = 200
_WD_Navigate ==> Success [0] : Parameters:   URL=http://192.168.0.7/404.php
_WD_LoadWait ==> Success [0] : Parameters:    Delay=Default    Timeout=Default    Element=Default
HTTP status: 200+>17:01:03 AutoIt3.exe ended.rc:0
+>17:01:03 AutoIt3Wrapper Finished.
````

##### Console (geckodriver.exe)
```
1658415658485   geckodriver::marionette DEBUG   Connection to Marionette established on 127.0.0.1:19988.
1658415661115   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"d41abbba-2dde-4ca9-99ac-5f2f9f381ad5","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"102.0.1","moz:accessibilityChecks":false,"moz:buildID":"20220705093820","moz:geckodriverVersion":"0.31.0","moz:headless":false,"moz:processID":30064,"moz:profile":"C:\\Users\\User\\AppData\\Local\\Temp\\rust_mozprofile9HwiWc","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"moz:windowless":false,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"10.0","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1658415661136   webdriver::server       DEBUG   -> POST /session/d41abbba-2dde-4ca9-99ac-5f2f9f381ad5/url {"url":"http://192.168.0.7/404.php"}
1658415661235   webdriver::server       DEBUG   <- 200 OK {"value":null}
1658415661247   webdriver::server       DEBUG   -> POST /session/d41abbba-2dde-4ca9-99ac-5f2f9f381ad5/execute/sync {"script":"return document.readyState", "args":[]}
1658415661267   webdriver::server       DEBUG   <- 200 OK {"value":"complete"}
```

### System under test

Please complete the following information.

- OS: Windows 10
- OS Arch.: x64
- Browser firefox
- Browser version 102.0.1

**Comment by vigri** [comment]
@Danp2 thanks for your reply.

> Please update your copy of WinHttp.au3 as indicated above.

Done. 1.6.4.1 --> 1.6.4.2

> * When I ran your code, I encountered the following errors:
Sorry Dan, my fault! - I've forgotten to add `http://` to URL here in the code. In my original .au3 the URL was prefixed with `http://`

This is the complete code now (without the includes and `SetupGecko()`)
```
Local $url = 'http://192.168.0.7/404.php'
Local $bHeadless = False
Local $sCapabilities = SetupGecko($bHeadless)
Local $iWebDriver_PID = _WD_Startup()
Local $sSession = _WD_CreateSession($sCapabilities)

If @error <> $_WD_ERROR_Success Then
	ConsoleWrite("Session not created..." & @error)
	Exit
EndIf

_WD_Navigate($sSession, $url)

ConsoleWrite("HTTP status: " & _WD_LastHTTPResult())

```

And finally a complete "overview" with all "changes"
![details](https://user-images.githubusercontent.com/2580723/180304582-1ad22c92-626e-4bf8-9d40-a160c29c79e0.png)

Still `200` instead of `404`

**Comment by Danp2** [comment]
> Still 200 instead of 404

Right.. which is correct AFAICS because that is the result being returned by the webdriver. It may not be possible to retrieve the browser's status code since we don't directly communicate with the it (the webdriver acts as an intermediary). You may want to review these threads from stackoverflow --

https://stackoverflow.com/questions/17657037/catching-a-404-error-with-selenium
https://stackoverflow.com/questions/6509628/how-to-get-http-response-code-using-selenium-webdriver

There are a couple of options that may allow you to obtain this information --

- Use _WD_ExecuteScript to run Javascript like in linked thread above
- I haven't checked, but some relevant information may be available via CDP.
- Webdriver Bidi APIs may help out in this area (bleeding edge stuff)

P.S. Can you share with us why you need this information?

**Comment by vigri** [comment]
@Danp2 sorry for the late feedback.

Thanks for your suggestions which put me in the right direction.


> P.S. Can you share with us why you need this information?
Yes, sure. I'm analyzing a service which response can be 200, 403 or 404.
If the status code is 403 additional steps need to be done (authentication) in order to get the data (200).
