### ISSUE TITLE
_WD_ElementSelectAction: Selecting options should fire Events

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#344]
### Describe the bug

In some cases selecting options should fire Change and Bubbles events.

### How to reproduce
You need to have specific websites which requires to fire event after options are selected

### Expected behavior

Event should be fired

### Screenshots

![image](https://user-images.githubusercontent.com/11089482/180866029-6c5e7d6d-ccac-49da-a3d6-4da57cad8e86.png)

### Additional context

WIP

### System under test

not related

**Comment by Danp2** [comment]
@mlipok You need to explain the function(s) involved. AFAICS, `_WD_ElementOptionSelect` should be fine as-is because it is simply clicking the found element, which should be sufficient to trigger the associated events.

**Comment by Danp2** [comment]
Fixed in #346
