### ISSUE TITLE
_WD_ElementSelectAction - Option status hidden 

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#345]
### Is your feature request related to a problem? Please describe

Option can have status hidden
```html
<option value="" disabled="" selected="" hidden="">Wybierz</option>
```

### Describe the solution you'd like

wondering if 

- multiSelect
- options
- selectAll

should check hidden status like currently they check for disabled status

### Describe alternatives you've considered

for now I only think about is it required.

### Additional context

none

**Comment by Danp2** [comment]
Yes, I think this would be a good enhancement.

**Comment by Danp2** [comment]
I also think `_WD_ElementSelectAction` / `options` needs to be expanded to include the hidden status.

**Comment by mlipok** [comment]
This was one of my intention which I mention here:

> wondering if
> 
> * multiSelect
> * options
> * selectAll

**Comment by Danp2** [comment]
OIC. I overlooked that in your post. 🙂

**Comment by mlipok** [comment]
If you have spare time.. do not hesitate.

**Comment by mlipok** [comment]
This issue can be closed as it is processed/continued in PR.
