### ISSUE TITLE
Click + Bubbles Event

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#351]
### Is your feature request related to a problem? Please describe

For some website I must to use such JS to fire event with `Bubbles` to properly click in element, and get the required action from website.
As so far I use my own wrapper function.

**I wonder where in `wd_helper.au3` I should to add such new features ? To which function ?**

### Describe the solution you'd like
I use such JS 
```autoit
Local $sScript = _
	"arguments[0].click();" & _
	"arguments[0].dispatchEvent(new Event('click', {bubbles: true}));" & _
	"return true;"
```

### Describe alternatives you've considered

as so far .. none.

### Additional context

This issue is related with my recent PR form :

https://github.com/Danp2/au3WebDriver/pull/333

https://github.com/Danp2/au3WebDriver/pull/346

**Comment by Danp2** [comment]
Your description of the problem is vague. Can you provide a short snippet of code that can be used to reproduce the issue? Currently I have no way of knowing which functions you are calling, the type of elements involved, etc.

**Comment by mlipok** [comment]
Will try to make repro code or even video.
But firstly must to find any public website with the need to use my code.

**Comment by Danp2** [comment]
FWIW, a video isn't helpful IMO. It would be good if you could better define the problem, ie --

- Which commands are failing to perform as expected?
- What element type is involved?
- Etc

**Comment by mlipok** [comment]
This is the same situation like with:

[Add check command in _WD_ElementActionEx](https://github.com/Danp2/au3WebDriver/pull/111/files)
and
[WD_SetElementValue $_WD_OPTION_Advanced usage](https://github.com/Danp2/au3WebDriver/pull/333/files)
and
[_WD_ElementSelectAction: Selecting options +Events](https://github.com/Danp2/au3WebDriver/pull/346/files)

But now I'm thinking about clicking into elements like `<buttons>`

btw.
and in other places like for example here:
```autoit
Func _WD_ElementStyle($sSession, $sElement, $sCSSProperty = Default, $sValue = Default)
	Local Const $sFuncName = "_WD_ElementStyle"
	Local $vResult, $iErr = $_WD_ERROR_Success
	Local $sJavaScript = ''

	If IsString($sCSSProperty) And $sValue <> Default Then ; set property value
		$sJavaScript = _
				"var element = arguments[0];" & _
				"element.style." & $sCSSProperty & " = '" & $sValue & "';" & _
				"element.dispatchEvent(new Event('change', {bubbles: true}));"
```


So now I have 2 questions:

1. Should we add dispatchEvent to   _WD_ElementStyle() - as I showed above ?
2. Should we add dispatchEvent to   _WD_ElementActionEx()  ?

**Comment by Danp2** [comment]
> Should we add dispatchEvent 

If the action being performed is designed to mimic a user's action (ie: clicking an element), then the dispatchEvent should occur. Otherwise, I don't believe it should occur by default.

>  to _WD_ElementStyle() 

In this case, I say "no" because you aren't performing an action that the end user can normally achieve on a webpage. 

> to _WD_ElementActionEx() 

Most of the "commands" performed by this function are using standard webdriver actions, so I would expect the dispatchEvent to already be occurring for these. Of the remaining ones, "check" and "uncheck" already perform the dispatchEvent. 

Which others do you believe need to trigger dispatchEvent?

**Comment by mlipok** [comment]
I have some new observations.
I need to systematize them and do further tests.

**Comment by mlipok** [comment]
> you aren't performing an action that the end user can normally achieve on a webpage.

In some of my solution I had to do such thing.
I mean I have to move a moveable DIV element to bo always on left top corner of the main window to be able to click on the element
Thus I have to set `left` and `top` atribute in style.
```html
<div id="renameDocumentForm:dialogChangeDocumentNameId" class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-draggable ui-overlay-hidden" role="dialog" aria-labelledby="renameDocumentForm:dialogChangeDocumentNameId_title" aria-hidden="true" style="width: 400px; height: auto; left: 474.469px; top: 304.953px; visibility: hidden; display: block; z-index: 1017;" aria-live="off">
```

But in fact upon reflection
I don't suppose it will affect other elements.

If it ever turns out to be needed, then we will take care of it.

You can close this issue.
