### ISSUE TITLE
_WD_GetFrameCount returns also hidden frames

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#359]
but it is related to 
```
_WD_ExecuteScript ==> Javascript Exception [21] : Error occurred when trying to ExecuteScript
_WD_FrameList ==> Javascript Exception [21] : Error occured on "null" level when trying to check atributes child frames #1
```
wchich mean that `_WD_GetFrameCount` is getting numbers  of frame in wrong way.
Working on.

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/issues/354#issuecomment-1200320823_

**Comment by Danp2** [comment]
> _WD_GetFrameCount is getting numbers of frame in wrong way

I would recommend that we discuss this before you go off on a tangent where you "fix" something that isn't really broken.

**Comment by mlipok** [comment]
Currently `_WD_GetFrameCount` uses: `return window.frames.length` which for JS returns 3  but the problem is that 2 frames are hidden an thus WebDriver is not able to enter this frames as was showed here:
https://github.com/Danp2/au3WebDriver/issues/354#issuecomment-1200320290

Working on.

**Comment by mlipok** [comment]
My fault.

**Comment by Danp2** [comment]
Please stop assuming that the existing functionality of _WD_GetFrameCount is wrong. That's simply your opinion, which has yet to be proven right / wrong.
