### ISSUE TITLE
_WD_CheckContext bug with _WD_Action($sSession, 'url')

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#361]
### Describe the bug
I started using `_WD_CheckContext` in all of my projects. On some systems my end users notice problems.
after testing I comes to such conclusions:

using:
```autoit
Local $sSession =''
.......
.......
.......
_WD_CheckContext($sSession)
```

on some systems this modified `_WD_Action` snippets :
```autoit
		Case 'title', 'url'
			$sResponse = __WD_Get($sURLCommand)
	_Log(@ScriptLineNumber & ' WD TESTING: ' & $sResponse)
			$iErr = @error

			If $iErr = $_WD_ERROR_Success Then
				$oJSON = Json_Decode($sResponse)
				$sResult = Json_Get($oJSON, $_WD_JSON_Value)
			EndIf
	_Log(@ScriptLineNumber & ' WD TESTING: ' )

		Case Else
```

reports to me:
```
! [ 6 / 0 ] : 458 WD TESTING: WinHTTP request timed out before Webdriver
! [ 6 / 0 ] : 465 WD TESTING: 
```

on other system it reports to me:
```
--> wd_core:458/62599 WD TESTING: 
! [ 1 / 0 ] : wd_core:465/62605 WD TESTING: 
```
the problem is that in the other case there is not setting for `$iErr = @error`

### How to reproduce
Just use:
```autoit
_WD_CheckContext('')
If @error Then MsgBox($MB_OK + $MB_TOPMOST + $MB_ICONERROR, "Error occured", "@error = " & @error & @CRLF & "@extended = " & @extended)
```
on different system as far as you get error.

### Expected behavior
`_WD_Action` **and any other function** should set error after JSON decoding like in the following snippet
```autoit
	If $iErr = $_WD_ERROR_Success Then
		$oJSON = Json_Decode($sResponse)
		If Not @error Then $sResult = Json_Get($oJSON, $_WD_JSON_Value)
		If @error Then $iErr = $_WD_ERROR_JSONParsing
	EndIf
```

### Screenshots

none

### Additional context

none

### System under test

As far tested with geckodriver

Failed on FF 102.0.1 64Bit
Works well on FF 91.12.0esr 32Bit

**Comment by mlipok** [comment]
Btw 
I specially add new  `$_WD_ERROR_JSONParsing` to have it possible to manage when/where the problem occurs.

**Comment by Danp2** [comment]
Honestly, I can't understand what you are trying to say / explain above. I would expect `_WD_CheckContext('')` to fail because you aren't passing it a valid session ID. This is what I got when I tried it --

```
__WD_Get: URL=HTTP://127.0.0.1:4444/session//url
__WD_Get ==> Unknown Command [16] : HTTP status = 405 ResponseText=HTTP method not allowed
_WD_Action ==> Unknown Command [16] : Parameters:   Command=url   Option=Default
_WD_CheckContext ==> Webdriver Exception [10]
```

What am I failing to comprehend? Were you expecting different results when the session ID isn't valid (technically missing because you passed in an empty string)?

As far as this statement --

> _WD_Action and any other function should set error after JSON decoding like in the following snippet

I'm sure that there are areas where the error checking can be improved upon. Feel free to submit a separate PR on that. However, I don't think that I would label an error from `Json_Get` as a "parsing" error. To me, that's better described as "not found".

If `Json_Decode` or `Json_Enccode` return an error, then I would agree that it may be due to a "parsing" error.

**Comment by Danp2** [comment]
That makes no sense to me. Did you post the wrong picture?

**Comment by mlipok** [comment]
Wait little more - I had some other problem to diagnose.

**Comment by Danp2** [comment]
Is there a real issue here or pebcak?

**Comment by mlipok** [comment]
real issue but needs more investigation as I use different capabilities setting then normally in `wd_demo.au3` and thus I'm investigating this remontly on my client's computer where I must to ask for computer time.

**Comment by mlipok** [comment]
btw.
it occured on two different location (pc/client/city).

**Comment by Danp2** [comment]
>  it occured on two different location (pc/client/city).

I suggest that you take some time to better define the problem because it's not clear to me what isn't working correctly.

**Comment by mlipok** [comment]
You can assign this to me.

**Comment by Danp2** [comment]
@mlipok Any updates on this issue?

**Comment by mlipok** [comment]
Oh soon.
I must dig to TeamViewer log and check where it was hit.
Then I can ask client to connect me to this computer and make new test.

**Comment by mlipok** [comment]
Not able to replicate.....
Closing for now.
