### ISSUE TITLE
 IsKeyword Return should be changed:   variable > const

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#365]
### Is your feature request related to a problem? Please describe

maybe
I notice few places where construction like this:
```autoit
Local $bNoUpdate = (IsKeyword($bForce)
```
are used.

I wonder about some kind of refactoring....

### Describe the solution you'd like
Set all this return values from `IsKeyword` checking from variable to const
```autoit
Local Const $bNoUpdate = (IsKeyword($bForce)
```

and for example in `_WD_SetTimeouts`
```autoit
$bIsNull = (IsKeyword($iScript) = $KEYWORD_NULL)
```
should be set on top of the script to be const, or should be declared on deeper scope level....

### Describe alternatives you've considered

none

### Additional context

none

**Comment by Danp2** [comment]
> variable > const

Yes, that's technically the correct usage. Feel free to submit a PR is if makes you feel better. 😉 

> should be set on top of the script to be const, or should be declared on deeper scope level....

See, that's the issue. `$bIsNull` is only used when `$iScript` doesn't equal `Default`. If you move this calculation to the beginning of the function, then it gets executed unnecessarily at times.

Yes, you could change the location in the function where the var/const is declared. However, I think you are "[splitting hairs](https://www.collinsdictionary.com/us/dictionary/english/split-hairs)" at this point.

**Comment by mlipok** [comment]
> Feel free to submit a PR is if makes you feel better

just after we finish other PR's.
