### ISSUE TITLE
_WD_FrameList / Frame visibility

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#388]
As TODO in the future:

_WD_FrameList should return information about visibility of the frame

for example:
https://stackoverflow.com/questions/19669786/check-if-element-is-visible-in-dom

![image](https://user-images.githubusercontent.com/11089482/186519722-2d7d707a-e1d4-49a4-af2b-92a05e6c4595.png)

@Danp2 if you agree plese reference this as new issue, as I think that, for now we should focus on merging this what we have currently already developed.

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/issues/362#issuecomment-1226302749_

**Comment by mlipok** [comment]
you can assign this issue to me

**Comment by mlipok** [comment]
Should we also get informationa about shadow roots ?

**Comment by Danp2** [comment]
Definitely not as part of _WD_FrameList. Please open a separate issue if you would like to discuss further.
