### ISSUE TITLE
_WD_FrameList - not always takes all frames

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#397]
### Describe the bug
`_WD_FrameList()` gets list of frames which is not always complete.
It is due to the fact that Not all frames document are load completly.

### How to reproduce
use this following code.
```autoit
Func UserTesting() ; here you can replace the code to test your stuff before you ask on the forum
	_WD_Navigate($sSession, 'https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe')
	_WD_LoadWait($sSession)

	; Example 1 - from 'https://www.w3schools.com' get frame list as string
	Local $sResult = _WD_FrameList($sSession, False)
	#forceref $sResult
	ConsoleWrite("! ---> @error=" & @error & "  @extended=" & @extended & " : Example 1" & @CRLF)
	ConsoleWrite($sResult & @CRLF)

	; Example 2 - from 'https://www.w3schools.com' get frame list as array
	Local $aFrameList = _WD_FrameList($sSession, True)
	ConsoleWrite("! ---> @error=" & @error & "  @extended=" & @extended & " : Example 2" & @CRLF)
	_ArrayDisplay($aFrameList, 'Example 2 - w3schools.com - get frame list as array', 0, 0, Default, 'Absolute Identifiers > _WD_FrameEnter|Relative Identifiers > _WD_FrameEnter|IFRAME attributes|URL|Body ElementID|IsHidden')

	; Example 2 - from 'https://www.w3schools.com' get frame list as array
	$aFrameList = _WD_FrameList($sSession, True)
	ConsoleWrite("! ---> @error=" & @error & "  @extended=" & @extended & " : Example 2 - again" & @CRLF)
	_ArrayDisplay($aFrameList, 'Example 2 - w3schools.com - get frame list as array - again', 0, 0, Default, 'Absolute Identifiers > _WD_FrameEnter|Relative Identifiers > _WD_FrameEnter|IFRAME attributes|URL|Body ElementID|IsHidden')
EndFunc
```
When first `_ArrayDisplay` is displayed wait at least 1 minute before you close the displayed array.
Compare second `_ArrayDisplay` result with the frst result.
Also check `window.top.document.querySelectorAll('iframe')` in browser console.

### Expected behavior

Always full list of frames.

### Screenshots

![image](https://user-images.githubusercontent.com/11089482/187792336-b8bdd789-8e2b-4e4b-ab7b-154607e833ad.png)

### Additional context

none

### System under test
not related

**Comment by mlipok** [comment]
please assign this issue to me.

btw.
I will try to fix it next few weeks, as this is not a pressing problem.

**Comment by mlipok** [comment]
After some thought.
It should be assumed that some websites work dynamically.
This means that the user/scripter should first bring the page to a static state.

However, if the website undergoes constant dynamic changes and the number of frames changes (e.g. advertisements appear and disappear), we are not able to ensure that the state of the website at the beginning when the function is called will be constant in time until the completion of the processing by this function , the more so that it is quite a complementary function that performs a lot of operations that can be extended in time even to many seconds.

.....

**Comment by mlipok** [comment]
I think that it should be taken as normal and despite everything (even in the case of an error), try to return the result that has been correctly processed so far, or even otherwise.
If the given information is no longer available, leave the field empty, without returning an error.

If you initially agree with this approach, let's say let's leave this task as pending, until other tasks are completed.

**Comment by mlipok** [comment]
> I think that it should be taken as normal and despite everything (even in the case of an error), try to return the result that has been correctly processed so far, or even otherwise. If the given information is no longer available, leave the field empty, without returning an error.
> 
> If you initially agree with this approach, let's say let's leave this task as pending, until other tasks are completed.

@Danp2 
Can you confirm that you agree or do you have other opinion ?

**Comment by Danp2** [comment]
Yes, I see the existing functionality as a "feature" rather than a bug since you can't gather data on an element that doesn't yet exist.

**Comment by mlipok** [comment]
> you can't gather data on an element that doesn't yet exist 

..... or disappeared during processing.
