### ISSUE TITLE
Call usage in wd_core.au3

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#409]
### Describe the bug

Any function that is placed in wd_helper.au3 and used in wd_core.au3 should be moved to wd_core.au3
This are : `_WD_GetFreePort` and `_WD_IsLatestRelease`
They are required to start browser instance thus they should be placed in `wd_core.au3` not in `wd_helper.au3`

### How to reproduce
not related

### Expected behavior
not related

### Screenshots
not related

### Additional context
it is a first step to make it possible to use:
```autoit
#AutoIt3Wrapper_Run_AU3Check=N
#AutoIt3Wrapper_Run_Au3Stripper=Y
#Au3Stripper_Parameters=/RM /SO /RSLN /PE
```

### System under test
not related

**Comment by Danp2** [comment]
>  They are required to start browser instance 

Required? I don't think so. Certainly not for a basic browser session. Feel free to elaborate if you disagree.

> Any function that is placed in wd_helper.au3 and used in wd_core.au3 should be moved to wd_core.au3

In my mind, these are both "helper" functions and therefore don't belong in wd_core, which is intended to hold only "core" webdriver functionality.

**Comment by mlipok** [comment]
Approx.
I will not argue further for now.
