### ISSUE TITLE
Extend _WD_ElementActionEx() by a remove option

### ISSUE THREAD

**Issue by Sven-Seyfert** [Danp2/au3WebDriver#416]
### What
I would like to extend `_WD_ElementActionEx()` by the command 'remove'.

### Why
Because there was a forum question/requirement to remove an element of the DOM.

### What would the changes look like
I guess it's quite simple and it would be similar to:

``` autoit
    Case 'hide'
        $iActionType = 2
        $sJavaScript = "arguments[0].style='display: none'; return true;"
```
Actually this:
``` autoit
    Case 'remove'
        $iActionType = 2
        $sJavaScript = "arguments[0].remove();"
```

### Questions
- Should I set up a pull request? @mlipok already voted YES 😅 . What about you @Danp2?
- I will test it, for sure. Should I provide a testing script or extend the `wd_demo.au3` file with an example? Or is this too much for such a simple addtion?
- Which files should I also update, in case I get the GO? 
  - readme, changelog?

Best regards
Sven

**Comment by mlipok** [comment]
for:
```autoit
    Case 'hide'
        $iActionType = 2
        $sJavaScript = "arguments[0].style='display: none'; return true;"
```
this function **_WD_ElementStyle()**   should be used.

**Comment by Danp2** [comment]
Yes,  you can submit a PR. Just update the one source file.  I can handle the others.

**Comment by Danp2** [comment]
P.S. You don't need my permission to submit  a PR for review. That's why this code is hosted here in the first place. 😉
