### ISSUE TITLE
_WD_CreateSession and WD_Demo extension

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#424]
### Is your feature request related to a problem? Please describe

I notice today problem like in this screenshot
![image](https://user-images.githubusercontent.com/11089482/221189889-6cdcad67-277f-420b-b0d3-0f80bcd6b233.png)

When I force UPDATE: to "64Bit+Force" then it works.
When I force UPDATE: to "32Bit+Force" still the same problem like on the screenshot above.

### Describe the solution you'd like

1. _WD_CreateSession ==> Webdriver Exception [10] should show "message" information in case of error.
`_WD_CreateSession ==> Webdriver Exception [10] - Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line`
2. in `SetupGecko` we should start using
```111
_WD_CapabilitiesAdd('binary', _WD_GetBrowserPath("firefox"))
```
btw. we do the same before in `SetupOpera()`

### Describe alternatives you've considered

none

### Additional context

none

**Comment by mlipok** [comment]
proposal
```autoit
Func SetupGecko($bHeadless)
	_WD_Option('Driver', 'geckodriver.exe')
	_WD_Option('DriverParams', '--log trace')
	_WD_Option('Port', 4444)

;~ 	Local $sCapabilities = '{"capabilities": {"alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts":true}}}'
	_WD_CapabilitiesStartup()
	_WD_CapabilitiesAdd('alwaysMatch', 'firefox')
	_WD_CapabilitiesAdd('browserName', 'firefox')
	_WD_CapabilitiesAdd('acceptInsecureCerts', True)
	; REMARK
	; using 32bit geckodriver.exe sometimes may require to set 'binary' capabilities,
	; using 64bit geckodriver.exe usually dosen't require to set this capability, but at the same time setting is not affecting the script
	; So this is good habit to setup for any case.
	_WD_CapabilitiesAdd('binary', _WD_GetBrowserPath("firefox"))
	If $bHeadless Then _WD_CapabilitiesAdd('args', '--headless')
	_WD_CapabilitiesDump(@ScriptLineNumber) ; dump current Capabilities setting to console - only for testing in this demo
	Local $sCapabilities = _WD_CapabilitiesGet()
	Return $sCapabilities
EndFunc   ;==>SetupGecko
```

**Comment by Danp2** [comment]
>     in SetupGecko we should start using _WD_CapabilitiesAdd('binary', _WD_GetBrowserPath("firefox"))

I'm fine with this. However, I would recommend calling _WD_GetBrowserPath, checking for errors, and then only perform the `_WD_CapabilitiesAdd('binary'` in the event that a path was found. We should update the related Opera code accordingly.

**Comment by Danp2** [comment]
> _WD_CreateSession ==> Webdriver Exception [10] should show "message" information in case of error.

I believe there's already code in _WD_CreateSession to handle this. I wonder why it isn't working? 🤔

**Comment by mlipok** [comment]
> > _WD_CreateSession ==> Webdriver Exception [10] should show "message" information in case of error.
> 
> I believe there's already code in _WD_CreateSession to handle this. I wonder why it isn't working? 🤔

I will dig in it

**Comment by mlipok** [comment]
Here is the reason:
![image](https://user-images.githubusercontent.com/11089482/221541543-ed1d4ee0-1e32-4e29-8a90-fecefed2bb6f.png)

**Comment by mlipok** [comment]
I was thinking about fix. But I leave it to you.

**Comment by Danp2** [comment]
Should be as simple as adding the line `$sMessage = Json_Get($oJSON, "[value][message]")` to the final `Else` section, right?

**Comment by mlipok** [comment]
Should be closed ?
