### ISSUE TITLE
Unable to switch between windows

### ISSUE THREAD

**Issue by ye7iaserag** [Danp2/au3WebDriver#426]
Both:
`_WD_Window($sSession, "switch", $aWindowHandles[0])`
`_WD_Window($sSession, "window", $aWindowHandles[0])`

Will always fail to switch context between multiple windows, so in a scenario where you click a link that opens a different browser window, you are stuck, also trying to switch to the current window will fail with the same error

Error:
```
__WD_Post ==> Invalid argument [5] : HTTP status = 400 ResponseText={"value":{"error":"invalid argument","message":"invalid argument: missing command parameters","stacktrace":"Backtrace:\n\t(No symbol) [0x00D337D3]\n\t(No symbol) [0x00CC8B81]\n\t(No symbol) [0x00BCB36D]\n\t(No symbol) [0x00C17EFF]\n\t(No symbol) [0x00C17544]\n\t(No symbol) [0x00BA5427]\n\t(No symbol) [0x00BA5B0E]\n\t(No symbol) [0x00BA5EEA]\n\tGetHandleVerifier [0x00FAABF2+2510930]\n\tGetHandleVerifier [0x00FD8EC1+2700065]\n\tGetHandleVerifier [0x00FDC86C+2714828]\n\tGetHandleVerifier [0x00DE3480+645344]\n\t(No symbol) [0x00CD0FD2]\n\t(No symbol) [0x00BA516A]\n\t(No symbol) [0x00BA4B96]\n\tGetHandleVerifier [0x00FF8C9C+2830588]\n\tBaseThreadInitThunk [0x769700F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77447BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77447B8E+238]\n"}}
```

**Comment by ye7iaserag** [comment]
Found it.
`_WD_Window($sSession, "switch", '{"handle":"' & $aWindowHandles[0] & '"}')` works like a charm
remember to wrap it in a json object

**Comment by Danp2** [comment]
FWIW, `_WD_Window` was recently enhanced so that it performs the switch even if you pass it a "raw" handle.
