### ISSUE TITLE
Webdriver.chm name of the file

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#435]
### Is your feature request related to a problem? Please describe

`Webdriver.chm` name is misleaded as it is not relatead strictly to WebDrirver.

### Describe the solution you'd like

rename the file to: `au3WebDriver.chm`

### Describe alternatives you've considered

none

### Additional context
https://www.autoitscript.com/forum/topic/209831-how-to-handle-close-button-click-in-edge-browser-while-using-webdriver/?do=findComment&comment=1514652

**Comment by Danp2** [comment]
This change will be reflected in the next release.
