### ISSUE TITLE
$aWD_ERROR_DESC SecurityError: Permission denied to access property

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#436]
### Is your feature request related to a problem? 
Should we use separate ERROR number when "SecurityError: Permission denied to access property" occurrs.

### Describe the solution you'd like
New separate error ?

### Describe alternatives you've considered
none

### Additional context
I get such error:
```
__WD_Post: URL=HTTP://127.0.0.1:4444/session/cf23cb00-6bb2-4221-9369-ca4ba5835292/execute/sync; Data={"script":"return window.frames[25].frameElement.outerHTML;", "args":[]}
__WD_Post ==> Javascript Exception [23] : HTTP status = 500 ResponseText={"value":{"error":"javascript error","message":"SecurityError: Permission denied to access property \"frameElement\" on cross-origin object","stacktrace":"@https://www.tutorialspoint.com/html/html_frames.htm#:2:7\n@https://www.tutorialspoint.com/html/html_frames.htm#:3:8\n"}}
_WD_ExecuteScript ==> Javascript Exception [23] : Error occurred when trying to ExecuteScript
```

when I was working on: https://github.com/Danp2/au3WebDriver/pull/434

**Comment by Danp2** [comment]
No, I don't believe that a separate error code would be beneficial here. However, _WD_ExecuteScript could display the contents of "message" from the JS response instead of the generic response currently given.

**Comment by mlipok** [comment]
Ok

**Comment by mlipok** [comment]
not planed

**Comment by mlipok** [comment]
not planed
