### ISSUE TITLE
checking $_WD_HTTPRESULT <> $HTTP_STATUS_OK

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#445]
### Is your feature request related to a problem? 

I was working on: https://github.com/Danp2/au3WebDriver/issues/438
I start wondering where `$iErr = $_WD_ERROR_Exception` is used.
And then I notice for example `_WD_Window()`:
```autoit
	If $iErr = $_WD_ERROR_Success Then
		If $_WD_HTTPRESULT = $HTTP_STATUS_OK Then

			Switch $sCommand
				Case 'close', 'frame', 'fullscreen', 'maximize', 'minimize', 'parent', 'switch'
					$sResult = $sResponse

				Case 'new'
					$oJSON = Json_Decode($sResponse)
					If Not @error Then $sResult = Json_Get($oJSON, "[value][handle]")
					If @error Then $iErr = $_WD_ERROR_JSONParsing

				Case Else
					$oJSON = Json_Decode($sResponse)
					If Not @error Then $sResult = Json_Get($oJSON, $_WD_JSON_Value)
					If @error Then $iErr = $_WD_ERROR_JSONParsing
			EndSwitch
		Else
			$iErr = $_WD_ERROR_Exception
		EndIf
	EndIf

	Return SetError(__WD_Error($sFuncName, $iErr, $sParameters), 0, $sResult)
EndFunc   ;==>_WD_Window
```

IMO handling cases like `$_WD_HTTPRESULT <> $HTTP_STATUS_OK` in function other than `__WD_Post/__WD_Get/__WD_Delete` and specifically not in `__WD_DetectError` is inproper.

Because:
`__WD_DetectError` is function that should:
```autoit:
; Description ...: Evaluate results from webdriver to identify errors.
```

### Describe the solution you'd like
All errors/cases like `$_WD_HTTPRESULT <> $HTTP_STATUS_OK` should be maintined by `__WD_DetectError` 

### Describe alternatives you've considered
None

### Additional context
https://github.com/Danp2/au3WebDriver/issues/438

**Comment by Danp2** [comment]
> IMO handling cases like $_WD_HTTPRESULT <> $HTTP_STATUS_OK in function other than __WD_Post/__WD_Get/__WD_Delete and specifically not in __WD_DetectError is inproper.

We often disagree on implementation / coding styles. In this case, I would say that it may not be "best design", but IMO it isn't improper. FWIW, some of these checks may no longer be required due to updated checks performed in `__WD_DetectError`.

AFAICS, the functions involved are `_WD_Window`, `_WD_FindElement`, and `_WD_ElementAction`. Each of these will need to be tested / researched to determine why the check is there (commented code would have helped here) and if it is still needed.

**Comment by mlipok** [comment]
So from what I understood:

You tentatively agree that we need to look at these Functions:    `_WD_Window`, `_WD_FindElement`, and `_WD_ElementAction`
and make the appropriate changes.

Am I right - do I understand correctly?

**Comment by Danp2** [comment]
Correct. If you check out commit https://github.com/Danp2/au3WebDriver/commit/b984f20f4742deebe0e04434c7a09b30acd23eb3, you will see that the comparison to `$HTTP_STATUS_OK` existed before `__WD_DetectError` was created, so I believe that these checks can be completely removed.
