### ISSUE TITLE
Functions should be checked for escaping strings

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#470]
`_WD_Storage()` SET should be checked if $vValue should be escaped with `__WD_EscapeString()`
`_WD_Storage()` GET should be checked if $vResult should be de escaped with `Json_StringDecode()`

_Originally posted by @mlipok in https://github.com/Danp2/au3WebDriver/issues/469#issuecomment-1537521321_

**Comment by Danp2** [comment]
@mlipok Please share your thoughts on this. Why do you think further encoding / decoding is needed here?

**Comment by Danp2** [comment]
Also, see https://github.com/Danp2/au3WebDriver/issues/466#issuecomment-1523859474, which could also be the solution here.

**Comment by mlipok** [comment]
`_WD_GetElementByRegEx()` 
https://github.com/Danp2/au3WebDriver/blob/81154aba09b8d2f894170b276659ce99f26b8fd0/wd_helper.au3#L3059-L3075

is this StringReplace still needed ?
https://github.com/Danp2/au3WebDriver/blob/81154aba09b8d2f894170b276659ce99f26b8fd0/wd_helper.au3#L3073

**Comment by TheDcoder** [comment]
@mlipok Not sure really, the change is complicated and I have forgotten the context. Best if you trace it out and see if it's still required :smile:

**Comment by Danp2** [comment]
https://github.com/Danp2/au3WebDriver/blob/81154aba09b8d2f894170b276659ce99f26b8fd0/wd_helper.au3#L3073
Based on my testing, this line is no longer required.

**Comment by mlipok** [comment]
Any testing snippet ?

**Comment by Danp2** [comment]
https://github.com/Danp2/au3WebDriver/pull/301#issuecomment-1137863798

😆

**Comment by mlipok** [comment]
my memory doesn't go that far 
;)

**Comment by Danp2** [comment]
Regarding _WD_Storage, I would suggest that this be handled in the same way as I recommend in https://github.com/Danp2/au3WebDriver/issues/466#issuecomment-1544627814
