### ISSUE TITLE
ChromeDriver download location is changing

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#473]
### Describe the bug

From [here](https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE) --

> The download location for ChromeDriver releases will change.
>
> This applies to both the old ChromeDriver Stable + Beta downloads at https://chromedriver.storage.googleapis.com/ as well as the old Canary downloads at https://chromedriver.chromium.org/chromedriver-canary. We won’t publish new downloads to these locations in the future.
>
> Consult [the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/) to learn about the new URL format. Use [@puppeteer/browsers](https://github.com/puppeteer/puppeteer/tree/main/packages/browsers) to easily download and launch browser + driver binaries, or build your own custom solution using [our JSON API endpoints](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints).

### How to reproduce

N/A

### Expected behavior

`_WD_UpdateDriver` will continue to work correctly with future releases of ChromeDriver

### To Do
- [ ] Implement fix for new download location
- [ ] Enable support for 64bit version of ChromeDriver

**Comment by Danp2** [comment]
```[tasklist]
### To Do
- [ ] Implement fix for new download location
- [ ] Enable support for 64bit version of ChromeDriver
```

**Comment by mlipok** [comment]
as an answer to: https://github.com/Danp2/au3WebDriver/pull/477#issuecomment-1574890073
I think we should copy old settings:
```
["chrome", "chrome.exe", "chromedriver.exe", False, "goog:chromeOptions", "'https://chromedriver.storage.googleapis.com/LATEST_RELEASE_' & StringLeft($sBrowserVersion, StringInStr($sBrowserVersion, '.') - 1)", "", '"https://chromedriver.storage.googleapis.com/" & $sDriverLatest & "/chromedriver_win32.zip"'],
```

for example:
```
["chromeold", "chrome.exe", "chromedriver.exe", False, "goog:chromeOptions", "'https://chromedriver.storage.googleapis.com/LATEST_RELEASE_' & StringLeft($sBrowserVersion, StringInStr($sBrowserVersion, '.') - 1)", "", '"https://chromedriver.storage.googleapis.com/" & $sDriverLatest & "/chromedriver_win32.zip"'],
```

just simply **chrome** >> **chromeold**

**Comment by Danp2** [comment]
@mlipok See https://github.com/Danp2/au3WebDriver/pull/477/commits/392947d934e333813c6389a3b04acb1cb74c1cd1

**Comment by mlipok** [comment]
Looks fine.
