### ISSUE TITLE
_WD_Alert($session, "GETTEXT") is not working on edge webdriver(113.0.1774.42)

### ISSUE THREAD

**Issue by hychul11** [Danp2/au3WebDriver#476]
### Describe the bug

_WD_Alert($session, "GETTEXT") is not working on edge webdriver(113.0.1774.42)

### System under test

Please complete the following information.

- OS: Windows 10
- OS Arch.: x64
- Browser edge
- Browser version 113.0.1774.50

**Comment by hychul11** [comment]
sorry Danp2,  my winhttp.au3 file seems to be incorrect
after change file, alert function is working, thanks

**Comment by Danp2** [comment]
Glad you got it working correctly. 🙂
