### ISSUE TITLE
au3WebDriver.chm without content

### ISSUE THREAD

**Issue by CoSNikO** [Danp2/au3WebDriver#494]
Bug report

au3WebDriver.chm opens with items but when you click to see the details is empty

Screenshots

![image](https://github.com/Danp2/au3WebDriver/assets/30650198/a192c435-fde7-4c1b-ba1a-56605b53644b)

- OS: Windows 11
- OS Arch.:  X64
- Browser EDGE
- Browser version 116.0.1938.54

**Comment by mlipok** [comment]
https://www.medicalconnections.co.uk/kb/Security-Issues-For-Displaying-CHM-Files

**Comment by Danp2** [comment]
Another possible cause is when the CHM file is stored on a network drive

https://www.helpscribble.com/chmnetwork.html
