### ISSUE TITLE
_WD_GetTable - returns the rows of the nested table

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#496]
### Describe the bug

When a Table contains a nested table, then _WD_GetTable also returns the rows for the nested table.

### How to reproduce

try to get table from here:
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_html_nested_table

### Expected behavior

The result should only include the outer/selected/desired set of table rows, not also the contents of the nested table.

### Additional context

none

### System under test

not related

### Fix proposal
```autoit
;~ 	If $sRowsSelector = Default Then $sRowsSelector = "tr"
	If $sRowsSelector = Default Then $sRowsSelector = ":scope > tbody > tr"
```

**Comment by mlipok** [comment]
Question:
should we do the same with:
```autoit
	If $sColsSelector = Default Then $sColsSelector = "td, th"
	If $sColsSelector = Default Then $sColsSelector = ":scope > tbody > tr > td, :scope > tbody > tr > th"
```

**Comment by mlipok** [comment]
btw.
; https://stackoverflow.com/questions/64842157
should be changed to:
; https://stackoverflow.com/a/64842239/5314940

**Comment by mlipok** [comment]
@Danp2 I'm waiting for your opinion here.

**Comment by Danp2** [comment]
Your proposed fix didn't produced the desired results for me. Here's my test code --

```autoit
; The contents of this file are read & executed by the UserFile() function in wd_demo.au3
; Changes can be made to this file and quickly tested without having to exit or even close browser
ConsoleWrite("! Code now executing from usertesting.au3" & @CRLF)

ConsoleWrite("- Test 2:" &amp; @CRLF)
_WD_NewTab($sSession, True)
_WD_Navigate($sSession, 'https://www.w3schools.com/howto/tryit.asp?filename=tryhow_html_nested_table')
_WD_LoadWait($sSession)

__SetVAR(0, _WD_FindElement($sSession, $_WD_LOCATOR_ByXPath, "//iframe[@id='iframeResult']"))
_WD_FrameEnter($sSession, $_VAR[0])

__SetVAR(1, _WD_GetTable($sSession, "//table"))
_ArrayDisplay($_VAR[1])

__SetVAR(2, _WD_GetTable($sSession, "//table"), ":scope > tbody > tr")
_ArrayDisplay($_VAR[2])
```

FWIW, I'm not sure that we need to change anything here since the existing functionality works in most cases and the user can override the selector as needed.

**Comment by mlipok** [comment]
> Your proposed fix didn't produced the desired results for me. Here's my test code --

becuase you have issue in the code

bad line:
```autoit
__SetVAR(2, _WD_GetTable($sSession, "//table"), ":scope > tbody > tr")
```
fixed line:
```autoit
__SetVAR(2, _WD_GetTable($sSession, "//table", ":scope > tbody > tr"))
```

entire example
```autoit
; The contents of this file are read & executed by the UserFile() function in wd_demo.au3
; Changes can be made to this file and quickly tested without having to exit or even close browser
ConsoleWrite("! Code now executing from usertesting.au3" & @CRLF)

ConsoleWrite("- Test 2:" &amp; @CRLF)
_WD_NewTab($sSession, True)
_WD_Navigate($sSession, 'https://www.w3schools.com/howto/tryit.asp?filename=tryhow_html_nested_table')
_WD_LoadWait($sSession)

__SetVAR(0, _WD_FindElement($sSession, $_WD_LOCATOR_ByXPath, "//iframe[@id='iframeResult']"))
_WD_FrameEnter($sSession, $_VAR[0])

__SetVAR(1, _WD_GetTable($sSession, "//table"))
_ArrayDisplay($_VAR[1], 'Test 1')

__SetVAR(2, _WD_GetTable($sSession, "//table", ":scope > tbody > tr"))
_ArrayDisplay($_VAR[2], 'Test 2')

```

**Comment by mlipok** [comment]
> I'm not sure that we need to change anything here since the existing functionality works in most cases and the user can override the selector as needed.

so at least remark in function header description about nested <table> element

**Comment by mlipok** [comment]
> > so at least remark in function header description about nested `<table>` element
> 
> That works for me.

I don't know what you meant here

**Comment by mlipok** [comment]
> > ":scope > tbody > tr > td, :scope > tbody > tr > th"
> 
> What are you expecting the results to be with this? I got an empty array with this code --

I was just wondering, but now I understand few minutes ago how this following code works
```autoit
		Local $sScript = "return [...arguments[0].querySelectorAll(arguments[1])]" & _
				".map(row => [...row.querySelectorAll(arguments[2])]" & _
				".map(cell => cell.textContent));"
```

thanks to this article and video
https://www.freecodecamp.org/news/javascript-map-how-to-use-the-js-map-function-array-method/

**Comment by Danp2** [comment]
> I don't know what you meant here

I was agreeing with your assessment that adding a remark to the function header would be a good alternative to actually changing the function's defaults.

**Comment by Danp2** [comment]
> ; Description ...: Return all elements of a table.

I suggest that we also review / modify this description. Technically, it is returning the text content of the elements, not the elements themselves. What do you think about this?

`; Description ...: Retrieve text from all matching elements of a table.`

**Comment by mlipok** [comment]
> I suggest that we also review / modify this description. Technically, it is returning the text content of the elements, not the elements themselves. What do you think about this?
> 
> `; Description ...: Retrieve text from all matching elements of a table.`

[Description changed](https://github.com/Danp2/au3WebDriver/pull/500/commits/5e7a403c447070425c85c5ee88dd8af85d606d4d)
