### ISSUE TITLE
_WD_GetTable - $sBaseElement as CSSQuery

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#497]
### Is your feature request related to a problem?
Why only `<table>` element is located by XPath ?
Why not supporting CSSQuery ?

### Describe the solution you'd like

current:
```autoit
Func _WD_GetTable($sSession, $sBaseElement, $sRowsSelector = Default, $sColsSelector = Default)
```
proposal:
```autoit
Func _WD_GetTable($sSession, $sSelector, $sStrategy = $_WD_LOCATOR_ByXPath, $sRowsSelector = Default, $sColsSelector = Default)
```

### Describe alternatives you've considered

none

### Additional context

none

**Comment by Danp2** [comment]
This would be a `script breaking change`

**Comment by mlipok** [comment]
I know, but the third and fourth parameters have been used recently (they were only added a few months ago).
Hardly anyone uses them other than in the `Default` value.
Whoever uses them should be aware of this and should easily correct the code after reading RELEASE NOTES.

The benefits are considerable because we unify the way of using this function so that it works like others, i.e. we extend it from its current form to a more standard one (so that all element selection strategies are possible).

**Comment by Danp2** [comment]
I agree (just wanted to document it). 

> proposal:  Func _WD_GetTable($sSession, $sSelector, $sStrategy = $_WD_LOCATOR_ByXPath, $sRowsSelector = Default, $sColsSelector = Default)

The rest of the functions specify `strategy`, then `selector`, so I recommend changing this as well for consistency. I know this will mean more effort initially for anyone that currently uses _WD_GetTable, but I believe it is the correct move to make.

**Comment by mlipok** [comment]
Tomorrow I create PR
