### ISSUE TITLE
Request of function "_WD_GetUDFVersion()" which returns $__WDVERSION

### ISSUE THREAD

**Issue by Sven-Seyfert** [Danp2/au3WebDriver#510]
### Is your feature request related to a problem? Please describe

In [this](https://www.autoitscript.com/forum/topic/211567-webdriver-add-function-wish/#comment-1530893) forum thread / discussion a user was asking for an explicit function to get the current UDF version.

@Danp2 : You did already mention that you don't see the need for it.

> [...] At this time, I don't see the need to add this function to the UDF because
> - the functionality already exists, albeit in a different format
> - there's nothing preventing you from creating your own wrapper function

But indeed it would help to reduce the "switch cases" in function `_WD_Option()` which would be a nice side effect.
Also in terms of consistency I would go this way. See functions `_WD_IsLatestRelease()` and `_WD_GetWebDriverVersion()`.

⚠ It's totally fine for me if you say "no" and close the issue. Otherwise, I would provide a PR for this.

### Describe the solution you'd like

``` autoit
; Variant 1
Func _WD_GetUDFVersion()
	Return $__WDVERSION
EndFunc
```

### Describe alternatives you've considered

``` autoit
; Variant 2
Func _WD_GetUDFVersion()
	Return _WD_Option('version')
EndFunc
```

### Additional context

See the conversation in the [thread](https://www.autoitscript.com/forum/topic/211567-webdriver-add-function-wish/#comment-1530893) .

### Influences and relationship to other functionality

Maybe, in case of "Variant 1" will be accepted, the function `_WD_Option()` will get reduced by the "switch case" `"version"`. I see no other impact.

Best regards
Sven

**Comment by Danp2** [comment]
> But indeed it would help to reduce the "switch cases" in function _WD_Option() which would be a nice side effect.

> Maybe, in case of "Variant 1" will be accepted, the function _WD_Option() will get reduced by the "switch case" "version". I see no other impact.

Removing this functionality from _WD_Option would be a script breaking change for any existing scripts that use this option, so I see no good reason for creating such a scenario.

**Comment by Sven-Seyfert** [comment]
Understood 🤔 . I am not sure of course, but I bet there are almost no one who uses `_WD_Option("version")`.
Is it worth to go with "Variant 2" or do you prefer to "... let us close this"?

**Comment by Sven-Seyfert** [comment]
To be honest, I rethinked the whole approach and believe it's not necessary to add another function which is simply a wrapper function of another one. Like @Danp2 initially said:

> [...] At this time, I don't see the need to add this function to the UDF because
> - the functionality already exists, albeit in a different format
> - there's nothing preventing you from creating your own wrapper function

=> If it's fine for you two, @Danp2 and @mlipok, let us close the issue here.
=> In case it's still important for the author of the idea, he/she could open an GitHub issue on his/her own.

**Comment by Danp2** [comment]
@Sven-Seyfert Glad you finally came to your senses. 😝
