### ISSUE TITLE
__WD_GetLatestWebdriverInfo() does not always work if old information is in local cache

### ISSUE THREAD

**Issue by wdouglascampbell** [Danp2/au3WebDriver#527]
### Describe the bug

I was attempting to update to the latest Edge webdriver using the _WD_UpdateDriver() function but no update was occurring even though I knew that the version I had was not as new as the one being offered online.

### How to reproduce

Call _WD_UpdateDriver("MSEdge", Default, Default, Default, True)

### Expected behavior

Latest driver downloaded.

### Additional context

I solved the issue by changing the InetRead call in __WD_GetLatestWebdriverInfo() function to include the option $INET_FORCERELOAD versus the default option of $INET_LOCALCACHE.  After making that change and calling _WD_UpdateDriver again, the actual latest release was found and downloaded.

### System under test

Please complete the following information.

- OS: Windows 11 Home
- OS Arch.: X64
- Browser: Edge
- Browser version: 129.0.2792.89

**Comment by Danp2** [comment]
Thanks for the report and the suggested solution.
