### ISSUE TITLE
WD_Alert GETTEXT function returns  wrong korean text 

### ISSUE THREAD

**Issue by hychul11** [Danp2/au3WebDriver#529]
### Describe the bug

WD_Alert GETTEXT function returns  wrong korean text 

### How to reproduce

Steps to reproduce the behavior (e.g.):

_WD_Alert($session, "GETTEXT")  return wrong text

- korean
"엑셀 업로드" 
-real value 
"?묒? ?낅줈?쒓?"

### Expected behavior

return correctly  korean text  "엑셀 업로드"

### System under test

Please complete the following information.

- OS:  Windows 10
- OS Arch.: X64
- Browser edge
- Browser version  131.]

**Comment by Danp2** [comment]
@hychul11 

- Are you able to post a short reproducer script that demonstrates the issue? 
- Can you show us a screenshot of the alert dialog?
- Have you run your script with `$_WD_DEBUG = $_WD_DEBUG_Full` and taken a look at the output in the log, which will likely show that the value being returned is coming from the webdriver and not being modified by the UDF.

**Comment by hychul11** [comment]
Sorry Dan2 !
I  solve it , It works after update winhttp.au3 1.6.2.5 -> 1.6.4.2
Thank you

**Comment by Danp2** [comment]
Thanks for letting us know the outcome
